### ISSUE TITLE
Feature request: disable cache for specific requests

### ISSUE THREAD

**Issue by DreaMinder** [storyblok/storyblok-js-client#10]
This is needed for cache invalidation to work. I'm using storyblok-nuxt wrapper, and here is how I understand caching strategy, correct me if I wrong:
1. User requests content
2. site makes request to /spaces/me to acquire cacheVersion
3. site makes request to storyblok cdn and recieves content
4. user makes same request
5. site makes request to /spaces/me to acquire cacheVersion
6. if cacheVersion is the same, site pulls content from memory cache. If not, see step 3.

Everything is correct? Ok. The problem is, request to /spaces/me shouldn't ever be cached, otherwise it will always return cached cacheVersion and it makes this strategy useless - we can't know if cacheVersion changed on storyblok server.
This issue would be solved if there were something like this:
`await Storyblok.get('/spaces/me', {cache: false})`

**Comment by DominikAngerer** [comment]
Your understanding is correct. You're able to add a query param with any kind of timestamp (eg. `cv=new Date()`) to the /spaces/me call to disable the caching as it will than hit the route. For nuxt you can use the `cv=new Date()` for the `spaces/me` call on the server and add it to your store to reuse it across your client.

**Comment by DreaMinder** [comment]
Thanks.
If someone will read this issue, I'll describe what works for me now with this cache strategy:

> The timestamp can either be a server side generated timestamp that receives an update if our webhook triggers a publish event or you fetch it every time you boot up your application.

On one of nuxt routes there is a logic inside of asyncData: 
`if(query.flushCache) app.$storyapi.flushCache(); `
And storyblok hook connected to this page with ?flushCache=true query string. So everytime someone publish something - cache is flushed, but this works only for production version: don't forget to disable cache on development.

@DominikAngerer Am I understand it right that I don't need cacheVersion at all with this approach? Or I should run request to 'spaces/me' along with flushCache() method to get new cacheVersion?

**Comment by pdub888** [comment]
I am having the same issue @DreaMinder  - and it's not clear in the documentation what I'm exactly supposed to do. Doing something simple like replacing images doesn't work unless I generate my project again and push it live. I'm trying to figure out exactly what to do here....

My nuxt config module:
`["storyblok-nuxt", {accessToken: process.env.NODE_ENV == "production" ? 'xxx' : 'yyy', clear: "auto", cacheProvider: "memory"}]`

My call in index.vue:
`asyncData(context){
		
		const options = {
			version: process.env.NODE_ENV == 'production' ? 'published' : 'draft'
		}
		const requests = [
			context.app.$storyapi.get('cdn/stories/home', options),
      	  	context.app.$storyapi.get('cdn/stories/featuredwork', options)
		]
		
		return Promise.all(requests).then(res=>{
			let peopledata = res[0].data.story.content.body.find((item) => item.component === 'PeopleSection');
			let content = res[0].data.story.content;
			
			return {
				peopledata,
				content
			}
		}).catch(errors=>{
			console.error(errors)
		})
		
	},`
	
	In this case, would I add if(context.flushCache) context.app.$storyapi.flushCache() right above const options?

**Comment by DreaMinder** [comment]
@pdub888 are you using `nuxt generate`? In this case, just disable cache: `cacheProvider: 'none'`, you don't need it when using static generation.

And regarding flushCache, I haven't used it for more than 2 years, so I won't be able to answer your question with confidence.

**Comment by pdub888** [comment]
Yes, I am - build then generate. Wouldn't that eliminate the power of cache so that users don't have to download new content every time they hit the site?

**Comment by DreaMinder** [comment]
No. With [nuxt-target-static](https://nuxtjs.org/blog/going-full-static/), storyblok-cache is completely pointless. 
It's meant to be used on a live server.

**Comment by pdub888** [comment]
I did not realize that. Thank you.
Of note, I was pointed here:
https://www.storyblok.com/docs/api/content-delivery#topics/cache-invalidation

And this seems to work:
`asyncData(context){
		
		// cacheing issue
		let cacheVersion = "";
		
		context.app.$storyapi.get('cdn/spaces/your-space-name', {})
		.then(response => {
			cacheVersion = response.data.space.version;
		}).catch(error => { 
		})
		
		const options = {
			version: process.env.NODE_ENV == 'production' ? 'published' : 'draft',
			"cv" : cacheVersion
		}`
		
Would you suggest just eliminating {clear: "auto", cacheProvider: "memory"} from my nuxt-config or sticking with the above solution?

**Comment by DreaMinder** [comment]
If I were you, I'd disable storyblok cache, as long as I have nuxt-target-static turned on. But if the above works for you, you can let it be...

**Comment by pdub888** [comment]
Unfortunately, actually none of the above works. Not even the above option that storyblok pointed out.

I have to export and push to show any changes - if i add new content, it would show, but replacing any content does not work - even when setting   target: 'static' and setting my storyblok nuxt module to:
["storyblok-nuxt", {accessToken: process.env.NODE_ENV == "production" ? 'xxx' : 'yyy', cacheProvider: "none"}],

And then saving my changes storyblok and hitting publish. Not sure if it's something in my async call that i'm doing wrong or something in storyblok that i'm doing wrong.

**Comment by DreaMinder** [comment]
So did you expect static content to change without rebuilding it? I got you wrong.
This is by design of **static** generation, the issue is not related to your code or storyblok config. 
If you need your content to be updated, set up CI\CD (or just use netlify) with storyblok [publish](https://www.storyblok.com/docs/Guides/using-storyblok-webhooks)-hook. Or turn off SSR. Or use a live server instead of static generation.

**Comment by katerlouis** [comment]
`cacheProvider: 'none'` is also not working for me in my nuxt ssg setup. 
@DreaMinder – the development server is kind of an SSR setup. Seeing cached content during development is no fun :F
