### ISSUE TITLE
After updating to 4.0.9, the Storyblok v2 endpoint is returning '422 Unprocessable Entity'

### ISSUE THREAD

**Issue by RPMXH** [storyblok/storyblok-js-client#105]
After updating from version 3.3.1 to 4.0.9, I began to receive 422 errors from the Storyblok API.

Every request that I send, such as this:

`https://api.storyblok.com/v2/cdn/stories/pt/news?version=published&is_startpage=1&cv=1622545739895&token=<TOKEN>`

Returns the error message:

`{
    "error": "Parameter(s) is_startpage not allowed"
}`

I have tried looking at the API's documentation, and the _**is_startpage**_ parameter is still there, and is documented exactly as the previous version of the API.

Even then, I have tested calling the API with the following parameter/value combinations, but it always returns a similar error error:
* is_startpage : 1 or 0 or true or false
* is_start_page :  1 or 0 or true or false
* isstartpage :  1 or 0 or true or false
* startpage :  1 or 0 or true or false
* start_page :  1 or 0 or true or false

If I perform the request without the _**is_startpage**_ parameter, the request does not return an error, but it returns much more data than what should really be obtained, and it is not an option for our solution.

Can you help me?

Edit 1: If you're interested I can also look in your backend and provide some help.

**Comment by RafaelMarquesVI** [comment]
Hello is there no update on this issue.

We have encountered a similar issue, whilst attempting to use the 4.X version of the api in some of our projects.

When is a fix scheduled to be released or announced?

**Comment by venux92** [comment]
Any news on this issue? we have the same issue after updating to the latest

**Comment by VojislavVlasic** [comment]
Hello!
We’ve created JS SDK Beta version for removed Axios and added TypeScript.
https://github.com/storyblok/storyblok-js-client/tree/5.0.0-beta
Please try it out with your projects and let us know if you find any bugs/issues.
