### ISSUE TITLE
Response's total header is always 1 when search_term param is used

### ISSUE THREAD

**Issue by cronin4392** [storyblok/storyblok-js-client#106]
I am running into an issue where if I pass `search_term` to a `storyblok-js-client` request, `total` is always coming back as 1.

[I found an issue](https://github.com/storyblok/storyblok/issues/660) on the Storyblok Github which appears to be the same. The reason I opened up a ticket here is that `total` is correct if I call the api directly (with a URL in my browser) but when I use the js client it's coming back as 1. Pagination and everything still works.

An example of my code:

```
Storyblok.get('cdn/stories/', {
    sort_by: 'published_at:desc',
    search_term: 'term',
    page: 1,
    per_page: 5,
})
```

**Comment by VojislavVlasic** [comment]
Hi @cronin4392 do you still need help?
