### ISSUE TITLE
HTTPS agent cannot be passed to axios

### ISSUE THREAD

**Issue by mbr74** [storyblok/storyblok-js-client#114]
For special enterprise proxy handling it will be great if "httpsAgent" property of axios config can be passed via Storyblok client config.

**Comment by mbr74** [comment]
should not get closed, sorry.

**Comment by VojislavVlasic** [comment]
Hello!
We’ve created JS SDK Beta version for removed Axios and added TypeScript.
https://github.com/storyblok/storyblok-js-client/tree/5.0.0-beta
Please try it out with your projects and let us know if you find any bugs/issues.
