### ISSUE TITLE
What's the suggested approach to connect storybridge to a nuxt static site in production?

### ISSUE THREAD

**Issue by katerlouis** [storyblok/storyblok-js-client#117]
I got storyblok bridge v2 up and running for our blog articles **when using localhost:3000 as the preview**. 
My editors don't have and cannot create a localhost environment, so we would need to use the production or staging environment for that.

But since we go full static with nuxt, the URL for an article in draft obviously hasn't been build yet on staging or production. 

![image](https://user-images.githubusercontent.com/1983382/123386925-77b41280-d597-11eb-9e4e-4e95f23ab5af.png)

How would you solve this issue?
What is the suggested way to preview new/unpublished content on a static site?

**Comment by TheCapedBaldi** [comment]
I'm quite curious. Have you managed to resolve this? I'm using Gatsby.

**Comment by VojislavVlasic** [comment]
Hi!
Please reach out to our customer support and they will assist you.
I'll close this issue.
