### ISSUE TITLE
setComponentResolver does not output actual vue components.

### ISSUE THREAD

**Issue by gijsroge** [storyblok/storyblok-js-client#118]
I can't seem to get compontentResolver working.

My components are all AsyncComponents. When I use the example from the docs I get this output:

![image](https://user-images.githubusercontent.com/2242498/128516173-1da4bbbf-e021-442b-88df-f41e040e5779.png)
_(removed the :blok prop content for this issue)_

My code:
```
useStoryBlok().setComponentResolver((component, blok) => {
  return `<component :blok='${JSON.stringify(blok)}'
                     is="${getStoryBlokComponent(component)}"></component>`
})
```

and the getStoryBLokComponent function:
```
export default function getStoryBlokComponent(identifier: string) {
  return defineAsyncComponent(() =>
    import(`./components/${pascalCase(identifier)}.vue`).catch(() => null)
  )
}
```

This is vue 3 btw.

My thought is that it's probably because I return a callback instead of a string with the component name. 
But that would mean you need to preload all your storyBlok components, which is bad for performance.

Any help is much appreciated.

**Comment by kasperstorgaard** [comment]
I did a bit of digging myself, and I am afraid that this is not possible at all in vue 2, and probably not in vue 3 either, if the approaches are similar behind the scenes

From docs:
https://vuejs.org/v2/guide/syntax.html#Raw-HTML

> The contents of the span will be replaced with the value of the rawHtml property, interpreted as plain HTML - data bindings are ignored. Note that you cannot use v-html to compose template partials, because Vue is not a string-based templating engine. Instead, components are preferred as the fundamental unit for UI reuse and composition.

I am not sure the example shown in the storyblok docs has never worked.

**Comment by gijsroge** [comment]
Yeah I agree, not possible. We disabled this feature for our client.
