### ISSUE TITLE
Code and types imply get() and getStory() only working with slug

### ISSUE THREAD

**Issue by renestalder** [storyblok/storyblok-js-client#119]
I'm a bit confused about the available methods to get a story. Based on the Storyblok API v2, I can get a story by its slug (default), but also by id or uuid if the corresponding parameter `find_by` is set. Yet, looking at the code of this library, the `get()` and `getStory()` functions imply they only take the slug as the first parameter (even though I probably could cast any id to a string and push it down the function and it might work).

Is this just an inaccurate parameter naming or does it only work with the slug?

**Comment by christianzoppi** [comment]
Hello @renestalder,

I understand the confusion. Those methods are there but they are not in the documentation and I believe that they are just older parts of the code. 
I would advise using the [GET method](https://github.com/storyblok/storyblok-js-client#method-storyblokget) explained in the readme file because that gives you the flexibility of using any endpoint of the Storyblok API with any parameter, including the one for fetching a single story.

I hope this helps you 😄

**Comment by renestalder** [comment]
@christianzoppi The same problem applies to the `get()` function. The first parameter is marked as `slug`, this applies to the [corresponding line in the typings](https://github.com/storyblok/storyblok-js-client/blob/master/types/index.d.ts#L187), but also the original code.

The confusion could probably be resolved by adding JSDoc comments with the parameter description to clarify that the parameter can not only hold the slug but also UUID and ID, or by renaming the parameter itself to something (hideous but verbose) like `slugOrIdOrUUID`.

**Comment by christianzoppi** [comment]
@renestalder The `get()` function is not meant to retrieve a single story, it is a method to use any endpoint from the [CDN API](https://www.storyblok.com/docs/api/content-delivery/v2), so we can't name parameters with a specific name related to a single endpoint.

**Comment by renestalder** [comment]
@christianzoppi

> we can't name parameters with a specific name related to a single endpoint.

I feel that's my point, but I seem unclear.

So, this is the get function:

```js
 get(slug, params) {
    let url = `/${slug}`
    const query = this.factoryParamOptions(url, params)

    return this.cacheResponse(url, query)
  }
```

It takes two parameters: The `slug` and the `params`. In the terminology of the Storyblok dataset, slugs look like this (taken from one of the response examples of the documentation):

* `"slug": "my-third-post"`
* `"full_slug": "posts/my-third-post"`

So now, I looked at the response examples and kind of though I knew what Is meant with the slug, when the function header looks like `get(slug, params)`. But turns out, I actually don't because slug means something different here.

In terms of the js client, the slug parameter looks like this:

* `"slug": "cdn/stories/posts/my-third-post"`

There's a mismatch of what the slug is in the response objects (the Storyblok data) and what it is in the js client functions. The terminology doesn't match, which leads to my main confusion: What's the correct way of calling these methods with the ID or the UUID?

So, If I'm not mistaken about my guess how this works, to consequently make this consistent with the Storyblok API documentation and resolve any confusion, applying the same naming internally and with JSDocs could help:

```js
 /**
  * @param {String} pathParam Full URL path including slug, UUID or ID e.g. cdn/stories/posts/my-third-post
  * @params {import(<whatssoeverPath>).StoryParams} queryParams 
  */
 get(pathParam, queryParams) {
    let url = `/${pathParam}`
    const query = this.factoryParamOptions(url, params)

    return this.cacheResponse(url, query)
  }
```

I hope this can clarify what I mean with the implication the `slug` parameter naming in the current implementation does to me.

**Comment by renestalder** [comment]
Or maybe, someone can clarify what is meant with `options` as the `get` function options parameter in the README is just linked to `https://www.storyblok.com/docs/api/content-delivery`.

If that function can get multiple results, do you mean the options from `https://www.storyblok.com/docs/api/content-delivery#core-resources/stories/retrieve-multiple-stories`?

(look, in general, I just have troubles to match the js client functions and descriptions to what I see in the API documentation)

**Comment by christianzoppi** [comment]
Thank you for the further explanation. I would advise checking the [readme](https://github.com/storyblok/storyblok-js-client#method-storyblokget), and not the code as that will be clearer. The first parameter of the `get` method is the endpoint of your request. The second parameter, options, is an object with the parameters of your request (so all the parameters/options that you can send to every endpoint).

There is no specific way for the JS client to perform requests, you need to check the CDN API docs for that and you will also find examples using the JS client if you select JavaScript in the top right corner of the page.

An example of what you asked above is just:
``` 
// Retrieve by uuid
const res = await client.get('cdn/stories/4791d9ef-1078-42d6-9bcc-cf92ded7af47', {
    version: 'draft' ,
    find_by: 'uuid'
})

// Retrieve by id
const res = await client.get('cdn/stories/64855044', {
    version: 'draft'
})

// Retrieve by slug
const res = await client.get('cdn/stories/home, {
    version: 'draft'
})
```

**Comment by nachoadjust** [comment]
Hello @christianzoppi !
I believe there is a type problem here where `find_by` is not a supported param of `ISbStoriesParams`:

```js
// Retrieve by uuid
const res = await client.get('cdn/stories/4791d9ef-1078-42d6-9bcc-cf92ded7af47', {
    version: 'draft' ,
    find_by: 'uuid' //  Argument of type '{ find_by: string; }' is not assignable to parameter of type 'ISbStoriesParams'
})
```

Could the get method be refactored to also accept `ISbStoryParams`?
https://github.com/storyblok/storyblok-js-client/blob/main/src/index.ts#L222

**Comment by AdrianFahrbach** [comment]
@christianzoppi Any updates on this?

I also don't think that this issue should be closed, since the types **heavily** imply that `getStory` is the way to go when searching for UUIDs even though that doesn't work for me.
