### ISSUE TITLE
add possibility to resolve links with the bridge like it is possible with the relations on inputs - https://www.storyblok.com/changelog#how-to-upgrade

### ISSUE THREAD

**Issue by Slackman2015** [storyblok/storyblok-js-client#121]
At the moment only relations can be resolved when one enters new content and the bridge fetches new content from the API but this doesn't exist for links yet. When one uses the resolve_links parameter and the implementation relies on the retrieved data it breaks in the preview when entering anything.

It would be very helpful to be able to have a solution similar to resolveRelations but for links=url|story.

**Comment by Rigo-m** [comment]
I am having the same problem. Why has this issue been closed?
