### ISSUE TITLE
Error when using `resolve_relations`

### ISSUE THREAD

**Issue by tricki** [storyblok/storyblok-js-client#130]
I followed the guide ["Creating global components and referencing them in Storyblok"](https://www.storyblok.com/tp/global-components-references) and when I set `resolve_relations` I get the following error:

`TypeError: Cannot read properties of undefined (reading 'forEach')`

The error comes from [this line](https://github.com/storyblok/storyblok-js-client/blob/a922c4d14589e02391d2e7ecd13c024aef54a9cf/source/index.js#L285). The response data has neither a `rel_uuids` nor a `rels` property.

Not sure if this is a bug or if I'm doing something wrong (I just started using Storyblok). If I manually set that variable to an empty array everything seems to be working.

**Update:**
The same thing happens when adding `resolve_links=url` as described in [this FAQ entry](https://www.storyblok.com/faq/link-object-history).

**Comment by Schinkentanz** [comment]
Hey @tricki, are you using the [management API](https://www.storyblok.com/docs/api/management)?
Seems like the `resolve_relations` option is not supported here 😞 
But it works for me with the [delivery API](https://www.storyblok.com/docs/api/content-delivery) 👍

**Comment by tricki** [comment]
You're right, I was using the management API without meaning to because I passed the token as `oauthToken` instead of `accessToken`.
It works now, thanks for the help.
