### ISSUE TITLE
Feature Request: Image URL builder

### ISSUE THREAD

**Issue by empz** [storyblok/storyblok-js-client#132]
Is there a plan to include an Image URL builder like Sanity? https://github.com/sanity-io/image-url

If not, would you accept a PR from the community?

**Comment by VojislavVlasic** [comment]
Sure thing, we'd be interested in a PR from the community.
Please keep in mind that this shouldn't use many 3rd party libraries as we don't want bloated code.
We're currently working on removing some 3rd party libraries on our end as we'd like to have leaner code.
Thank you!
