### ISSUE TITLE
Language prefixes now forced in resolved relation urls

### ISSUE THREAD

**Issue by mattanglin** [storyblok/storyblok-js-client#133]
Our team uses this library via [gatsby-source-storyblok](https://github.com/storyblok/gatsby-source-storyblok) and recently tried updating to find that one of the recent releases has created a breaking change in our codebase. The [v4.1.4 release](https://github.com/storyblok/storyblok-js-client/releases/tag/v4.1.4) [added "default" language to all resolved relations](https://github.com/storyblok/storyblok-js-client/commit/8b91deb199951c2b2804e29739caffa6c287ed61) which I imagine is great if you're using Storyblok with i18n/l10n as this now resolves all link objects to have a `cached_url` property that is always prefixed with a language (in the default case `default/`). Our team is not using translations and can't find a way to resolve relations **_without_** sending the default language parameter.
We're currently locking our version to v4.1.3, but this obviously isn't sustainable.

**Comment by sherakama** [comment]
Related: https://github.com/storyblok/gatsby-source-storyblok/issues/50

**Comment by mattanglin** [comment]
Resolved by #140
