### ISSUE TITLE
RichTextResolver.render doesn't throw an exception

### ISSUE THREAD

**Issue by jarkt** [storyblok/storyblok-js-client#138]
```
const resolver = new RichTextResolver()
resolver.render(undefined)
```

If you call the RichTextResolver.render method with a wrong content type, it doesn't throws an exception as one would expect, but writes a message on console output. I cannot programmatically handle this case.

Usually all the log output in our project is in JSON format. I don't think, that a library should write to the console.

https://github.com/storyblok/storyblok-js-client/blob/f0a6eed3c8e99057bd6b52b04741f63d8d7d1ae5/source/richTextResolver.js#L50

**Comment by VojislavVlasic** [comment]
Hello!
We’ve created JS SDK Beta version for removed Axios and added TypeScript.
https://github.com/storyblok/storyblok-js-client/tree/5.0.0-beta
Please try it out with your projects and let us know if you find any bugs/issues.

**Comment by jarkt** [comment]
It's not relevant for me anymore because I currently don't have a storyblok based project.
