### ISSUE TITLE
[Feature Request] GraphQL api integrate

### ISSUE THREAD

**Issue by jerryeechan** [storyblok/storyblok-js-client#150]
I have successfully do the graphQL api call with this
```js
axios({
    method: "get",
    url: "https://gapi.storyblok.com/v1/api",
    params: { query: query },
    headers: {
      Token: "---Preview---",
      Version: "draft",
    },
  });
 ```
I think it would be nice to integrate GraphQL api into StoryBlokClient.

**Comment by VojislavVlasic** [comment]
Hello @jerryeechan, hope you're doing well.
We've reviewed this FR and we won't be moving forward with it.
It would create a lot of maintenance overhead to keep the Apollo dependency up to date and we're also working on shrinking down the JS client.
Thank your for your suggestion.

**Comment by bartelemi** [comment]
This is a bit disappointing, what is the recommended way of having mixed graphql/rest endpoints in a single app in this situation? We're having to duplicate a lot of set-up logic currently to achieve that.

**Comment by VojislavVlasic** [comment]
Hello @bartelemi , that is the only way to achieve this mixed implementation as far as I know.
