### ISSUE TITLE
[FEATURE Proposal] Error Management Interface

### ISSUE THREAD

**Issue by imabp** [storyblok/storyblok-js-client#151]
It will be a nicer idea to build an error management interface for `storyblok-js-client` . This helps developers with more context to different kind of errors. 

What is an Error Management?
Something similar to this AWS Article [here](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-managing-errors.html)

Proposal
 - Building an interface having all kind of Errors.
 - This interface can be used by developers to handle the errors effectively, instead of writing their own custom error management.
 - Brings consistency and better error handling.

**🚀** Open to suggestions

**Comment by VojislavVlasic** [comment]
Hello!
We’ve created JS SDK Beta version for removed Axios and added TypeScript.
https://github.com/storyblok/storyblok-js-client/tree/5.0.0-beta
Please try it out with your projects and let us know if you find any bugs/issues.

**Comment by imabp** [comment]
Yes, I tried the stable version on main, it did require me to install `axios` separately.
Will give this beta a try.
