### ISSUE TITLE
Bugged request URL when using get function on Node (next.js)

### ISSUE THREAD

**Issue by maxeth** [storyblok/storyblok-js-client#174]
Hello,

I was just about to use the client ```v4.2.0```  on the server-side of my Next.js ```v11.1.3``` application, and noticed that every single request that is being made via ```Storyblok.get()``` has a bugged out URL: 

Instead of ```/v1/cdn/stories``` the request is being made to ```/v1/%0A%20%20%20%20%20%20%20%20/cdn/stories```  so there seem to be some unwanted characters ('+' ?) added to the url which are then being escaped.

This is how I create the client inside my Next.js API route:

```
import StoryblokClient from "storyblok-js-client"
// also tried: const StoryblokClient = require("storyblok-js-client/dist/es5/index.cjs");

const Storyblok = new StoryblokClient(
  {
    accessToken: process.env.STORYBLOK_PREVIEW_TOKEN,
  },
  "https://api.storyblok.com/v1"
);
```

It works perfectly fine on the client-side, and I tried logging the url right before the request is made and the weird part between ```v1``` and ```cdn``` is not there. 

Is there any required Node-side configuration that's different from the client-side that I'm missing?

**Comment by VojislavVlasic** [comment]
Hi,
Please create an issue here:
https://github.com/storyblok/react-next-boilerplate
Or reach out to our customer support.
Thank you!
