### ISSUE TITLE
Resolve relations only returning a max of 25 stories

### ISSUE THREAD

**Issue by chrisix22** [storyblok/storyblok-js-client#180]
When resolving relations and there are more than 25 stories, it's only returning the first 25. The remaining are still unresolved UUIDs.

`      storyblokInstance.on('input', (event) => {
        // live updates when editing
        setStory(event.story);
      });`

**Comment by VojislavVlasic** [comment]
Hi @chrisix22 !
The SDK should resolve all stories, it essentially loops enough times until everything is resolved.
Every loop is 50 items.
So I'm not sure why you'd get just 25 items resolved.
Can you please tell me what's the latest version that's working for you?

**Comment by VojislavVlasic** [comment]
Hello!
We’ve created JS SDK Beta version for removed Axios and added TypeScript.
https://github.com/storyblok/storyblok-js-client/tree/5.0.0-beta
Please try it out with your projects and let us know if you find any bugs/issues.
