### ISSUE TITLE
Rich Text Resolver ES Module Missing?

### ISSUE THREAD

**Issue by philipdanielhayton** [storyblok/storyblok-js-client#194]
Howdy,

What's the correct way to import RichTextResolver in v4.3.1? `import RichTextResolver from 'storyblok-js-client/dist/rich-text-resolver.es';` no longer works for me, it looks like the .es file is missing from node_modules.

**Comment by awacode21** [comment]
i am experiencing the same issue

**Comment by edmeehan** [comment]
[Looks related to this update](https://github.com/storyblok/storyblok-js-client/commit/3c6009bd50de837110ba77bb367063b270f414ca#diff-6814bf77564b4f1c92f5861e184e28fe217c080a047fefa8b73a728f755ec45cL89)

**Comment by thiagosaife** [comment]
Hello @philipdanielhayton 

Could post how you are doing the import? I need to know if you have a 'use strict' in your application, for example. Are you trying to use import under a `commonjs` file? For example, if you try to use the `.es` extension from a const variable, you will probably get an error. Please share you file, so I can have a look on how are you doing the import. 
**Don't forget to erase any sensitive data before posting here.**

Thanks!

**Comment by thiagosaife** [comment]
Hello guys. Is this issue still happening?

**Comment by philipdanielhayton** [comment]
Hi Thiago,

Apologies for not getting back to you. I'm unable to test if this is working now as I ended up switching to Markdown in the project. However I was importing the file in a svelte component using TS, and yes IIRC I belive it was in strict mode.

Feel free to close this issue if you like, hopefully it's been resovled now.

**Comment by thiagosaife** [comment]
Hi @philipdanielhayton 

No need to apologize. I will close this issue but feel free to open new issues as they might be necessary. And thanks for the help.
