### ISSUE TITLE
Resolve Relations Broken in >4.0.0

### ISSUE THREAD

**Issue by ryanwhitemedia** [storyblok/storyblok-js-client#199]
I have some code working in 3.3.1

```
 let { data } = await Storyblok.get(`cdn/stories/${slug}?resolve_relations=team_members`, sbParams);
```
<img width="428" alt="Screen Shot 2022-04-21 at 12 01 40 AM" src="https://user-images.githubusercontent.com/17152119/164369586-ffdb7fd6-9edd-48c9-81d4-5bbf3f220954.png">

When I upgraded to 4.2.1 it stopped working. Same line of code but this is the result. I tested with 4.2.1 and 4.3.1 and still get the same result.

<img width="443" alt="Screen Shot 2022-04-21 at 12 02 16 AM" src="https://user-images.githubusercontent.com/17152119/164369636-16670b3e-0b3f-4cdf-bbf5-142e8269744f.png">

**Comment by ryanwhitemedia** [comment]
I did a follow up. Everything 4.0.0 and up has the same issue, 3.3.1 is the latest the resolve relations works in.

**Comment by johannesdz** [comment]
Same issue here. We are currently mapping it manually, but this job should be done by the client.

Maybe it helps to someone:

`const story: any = foundStoryResult.data.story;
if (story.content?.categories?.length) {
	story.content.categories = story.content.categories.reduce((list: any[], categoryUUID: string) => {
		const category: any = foundStoryResult.data.rels.find((item: any) => item.uuid === categoryUUID);
		if (!category) {
			return list;
		}
		list.push(category);
		return list;
	}, []);
}`

@ryanwhitemedia , your team_members is our categories.

**Comment by VojislavVlasic** [comment]
We'll close this issue.
The resolve_relations should be passed as a parameter.
Probably in the past it was allowed to add querystring parameters in the URL but the way we advise to use it in our docs is to add everything in the parameters and we’ll take care of converting them to a querystring if it’s a GET request.
If you need further support please reach out to our customer support.

**Comment by johannesdz** [comment]
@VojislavVlasic , i am using resolve_relations in the SDK, but its still not working. It would be great, if you could reopen this ticket.

**Comment by VojislavVlasic** [comment]
@johannesdz sure thing.
Please reach out to our support team and provide them with more info so that we can figure out what's wrong.
We'd need your code, what you're currently getting and what you used to get.
We'll look into this as soon as possible.

**Comment by VojislavVlasic** [comment]
@johannesdz can you email me: vojislav.vlasic@storyblok.com with the code you're using along with what you're getting now and what you we're getting before.
We'll look into this as soon as possible.

**Comment by VojislavVlasic** [comment]
Hello @ryanwhitemedia, just to check, are you still experiencing issues with the newest version?

**Comment by jstheoriginal** [comment]
I just had this issue, and was able to resolve it by doing the following:

---

In the past, you could provide just the field name, such as: `author` and it would resolve it within the story component you're dealing with.

Now, you must put the component type in front for it to resolve it properly, such as: `article.author`.

Once you make that change, it should work again.

The documentation for `resolve_relations` and the tutorial example helped clue me in that it's more strict now than in the past: https://www.storyblok.com/docs/api/content-delivery/v2#core-resources/stories/retrieve-one-story

<img width="741" alt="Screen Shot 2022-05-19 at 1 19 24 PM" src="https://user-images.githubusercontent.com/5117473/169372366-7ea9ea0e-b337-4482-9bc1-649ac191ad56.png">

---

So I think to resolve it for you, you'd need to do this instead:

```
let { data } = await Storyblok.get(`cdn/stories/${slug}?resolve_relations=company-page.team_members`, sbParams);
```

**Comment by VojislavVlasic** [comment]
Hi @jstheoriginal,
Thank you for letting us know!
We're glad you managed to resolve it on your end as we were scratching our heads - it's working just fine on our end.
For everyone else, I'll close this issue as this should be good enough fix.
