### ISSUE TITLE
object-hash is a heavy dependency

### ISSUE THREAD

**Issue by moltar** [storyblok/storyblok-js-client#2]
`object-hash` is 35kb, which is a pretty heavy overhead for a frontend. Are there maybe alternative ways a cache key can be calculated?

**Comment by onefriendaday** [comment]
True. object-hash dependency has been removed in the newest version 1.0.8.
Instead the lightweight module qs is used for parameter serializing.

**Comment by moltar** [comment]
Are you sure the `qs.stringify` code is deterministic? It may or not may be, I didn't really check. But if it's operating on objects without sorting keys, the order may change from call to call.

**Comment by moltar** [comment]
Ok, so it does support key sorting, but it is not enabled by default:

https://github.com/ljharb/qs/blob/2b94ea726fb4fe5d8c7b9bd2ee5cfb4d93dad89d/lib/stringify.js#L77-L78

But params for `stringify` are a bit out of hand 🤣 

```js
var stringify = function stringify( // eslint-disable-line func-name-matching
    object,
    prefix,
    generateArrayPrefix,
    strictNullHandling,
    skipNulls,
    encoder,
    filter,
    sort,   <-- need this guy
    allowDots,
    serializeDate,
    formatter,
    encodeValuesOnly
)
```

**Comment by onefriendaday** [comment]
Thank's

Something like the following would do the trick:

```
function alphabeticalSort(a, b) {
    return a.localeCompare(b);
}
qs.stringify({ a: 'c', z: 'y', b : 'f' }, { sort: alphabeticalSort })
```
