### ISSUE TITLE
Upgrade to core-js 3

### ISSUE THREAD

**Issue by andreiho** [storyblok/storyblok-js-client#20]
After upgrading `core-js` to version 3, I get this error:

```
Error: Cannot find module 'core-js/modules/es6.function.name'
```

Upgrading the babel plugin to v3 should do the trick. [See here.](https://babeljs.io/blog/2019/03/19/7.4.0#migration-from-core-js-2)

**Comment by onefriendaday** [comment]
Thanks for the report

We created a feature branch vor v3.
`npm install --save storyblok/storyblok-js-client#feature/corejs-3`

**Comment by LukasMachetanz** [comment]
I have the same problem when using the `storyblok-js-client` in an `Angular` (version 8) project.

The error looks like this:
`
ERROR in ./node_modules/storyblok-js-client/dist/throttlePromise.js
Module not found: Error: Can't resolve 'core-js/modules/es6.function.name' in '/Users/machetanz/DEV/design-system/node_modules/storyblok-js-client/dist'
`
Currently I installed the version `2.5.4` of `core-js` to fix this error. Is there a better approach than installing an older/deprecated version of `core-js` to fix this error? 

Thanks in advance. :)

**Comment by andreiho** [comment]
@LukasMachetanz Update `storyblok-js-client` to 1.0.28, this version depends on core-js@3.

**Comment by LukasMachetanz** [comment]
@andreiho The error occurred with this version. I assume that should not be the case if you are suggesting this as a solution?

**Comment by andreiho** [comment]
@LukasMachetanz If you depend on storyblok-js-client@1.0.28 and core-js@3 you shouldn't have any problems. At least I don't anymore.

**Comment by LukasMachetanz** [comment]
I tried it in a new project; it is working now. Thank you for your help and the quick answer. Sorry that I had to bother you again.

SOLVED & CLOSED ;)

**Comment by samhiddenhand** [comment]
On brand new create-react-app installs, the latest version of storyblok-js-client still gives this error, and the error found at https://github.com/storyblok/storyblok-js-client/issues/23 I'm able to resolve it by using the storyblok/storyblok-js-client#feature/corejs-3 feature branch, but that doesn't seem to have Storyblok.richTextResolver in it... Is there any way to update the main current version so that it installs correctly with create-react-app on a fresh install?

**Comment by samhiddenhand** [comment]
To follow up on my comment, I just noticed that when I run an npm install of storyblok-js-client without specifying which version, it installs an older version. I manually specified the latest version, and things seem to work.

**Comment by andreiho** [comment]
It looks like the latest tag is wrong in npm: https://www.npmjs.com/package/storyblok-js-client

**Comment by jajouka79** [comment]
in my project deps i have :

`    "core-js": "^3.3.2",
    "storyblok-js-client": "storyblok/storyblok-js-client#feature/corejs-3",
`
and in dev-deps :

`    "storyblok-migrate": "^0.3.3",`

when i run 

`npx storyblok-backup --components --stories`

i get the same error:
` Cannot find module 'core-js/modules/es6.function.name'
Require stack:
- /Users/si/Sites/another-tomorrow/node_modules/storyblok-migrate/node_modules/storyblok-js-client/dist/throttlePromise.js
- /Users/si/Sites/another-tomorrow/node_modules/storyblok-migrate/node_modules/storyblok-js-client/dist/index.js
- /Users/si/Sites/another-tomorrow/node_modules/storyblok-migrate/utils/api.js
- /Users/si/Sites/another-tomorrow/node_modules/storyblok-migrate/services/component.js
- /Users/si/Sites/another-tomorrow/node_modules/storyblok-migrate/cli-backup.js `


is this a related issue?

**Comment by jajouka79** [comment]
in the node_modules/storyblok-js-client/package.json the version is :

` "name": "storyblok-js-client",
  "version": "1.0.28",`

**Comment by andreiho** [comment]
@jajouka79 Try using storyblok-js-client 2.
