### ISSUE TITLE
Breaking change in 4.5.0 with `resolve_relations`

### ISSUE THREAD

**Issue by Cherry** [storyblok/storyblok-js-client#213]
Previously in version `4.4.0`, code like this would work, and relations would be resolved as expected:

```js
const storyblokOpts = {
	starts_with: 'foobar/xxx',
	per_page: 100,
	sort_by: 'name:asc',
	resolve_relations: 'xxx.yyy,xxx.bbb',
};
const results = await storyblok.getAll(`cdn/stories`, storyblokOpts);
```

In `4.5.0`, the relations are no longer resolved, and the `yyy` and `bbb` fields in that example are simple arrays of UUIDs. If I manually force the API to use version 1 via `'https://api.storyblok.com/v1/'` as shown in #183, I can restore this functionality, but I imagine this now being broken with the v2 API isn't intended, and is a breaking change.

**Comment by ttstauss** [comment]
I'm facing the same issue when attempting to update the package from `4.4.0`.

**Comment by ahmad-IW** [comment]
Having same issue on all versions after 4

**Comment by VojislavVlasic** [comment]
@Cherry, thank you for that info.
My email is vojislav.vlasic@storyblok.com

**Comment by VojislavVlasic** [comment]
We're looking for some additional info about this issue so that we can resolve it as soon as possible.
So if you guys can email me that would be great :)

**Comment by Cherry** [comment]
> We're looking for some additional info about this issue so that we can resolve it as soon as possible. So if you guys can email me that would be great :)

Email sent, thanks @VojislavVlasic.

**Comment by jstheoriginal** [comment]
I just had this issue, and was able to resolve it by doing the following:

---

In the past, you could provide just the field name, such as: `author` and it would resolve it within the story component you're dealing with.

Now, you must put the component type in front for it to resolve it properly, such as: `article.author`.

Once you make that change, it should work again.

The documentation for `resolve_relations` and the tutorial example helped clue me in that it's more strict now than in the past: https://www.storyblok.com/docs/api/content-delivery/v2#core-resources/stories/retrieve-one-story

<img width="741" alt="Screen Shot 2022-05-19 at 1 19 24 PM" src="https://user-images.githubusercontent.com/5117473/169372366-7ea9ea0e-b337-4482-9bc1-649ac191ad56.png">

**Comment by ahmad-IW** [comment]
After version 4 (currently using 3.3.1)
when trying to use resolve_relation I still get error on JS client, (can get it on direct API call, but get error on storyblok js client) 
This started last week , not sure if you changed any internal APIs

**Comment by ahmad-IW** [comment]
email sent as well @VojislavVlasic

**Comment by chrillep** [comment]
@VojislavVlasic ping?

**Comment by VojislavVlasic** [comment]
@chrillep we're still looking into this, as suggested by @Cherry 4.4.0 and 4.5.2 should work just fine.
You can also email me with your code, space ID and results for 4.4.0 and 4.5.0, that might help the investigations and fixes.

**Comment by thiagosaife** [comment]
Hello friends. @Cherry, @ahmad-IW, @chrillep, could you please get the [latest SDK's version](https://github.com/storyblok/storyblok-js-client/releases/tag/v4.5.6) and test again? Thanks a lot!

**Comment by VojislavVlasic** [comment]
Perfect, thank you very much for your help!
