### ISSUE TITLE
Fetching assets via the Storyblok management API doesn't work anymore 

### ISSUE THREAD

**Issue by Schinkentanz** [storyblok/storyblok-js-client#218]
Hey there,

when trying to fetch assets with ``await Storyblok.get(`spaces/${process.env.SB_SPACE_ID}/assets`)`` using `v4.4.0` and above, the following error occurs:
```
TypeError: Cannot read properties of undefined (reading 'content')
    at module.exports.iterateTree (/Users/<redacted>/workspace/<redacted>/node_modules/storyblok-js-client/dist/index.cjs.js:6:7474)
    at module.exports.resolveAssetsRelations (/Users/<redacted>/workspace/<redacted>/node_modules/storyblok-js-client/dist/index.cjs.js:6:8869)
    at /Users/<redacted>/workspace/<redacted>/node_modules/storyblok-js-client/dist/index.cjs.js:6:9322
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Here is a reproduction using a very minimal next.js API route: https://stackblitz.com/edit/nextjs-o1mzbc?file=pages%2Fapi%2Ftest.js,package.json Please make sure to fill in a correct Storyblok OAuth Token and a matching Space-ID in line 3 & 4. Then you can navigate to `/api/test` in the right pane to trigger the error.

The error occurs here, because `story` is `undefined` when calling `iterateTree` in line [369](https://github.com/storyblok/storyblok-js-client/blob/e337bbbc936988a6e65d5c21da9df4adb20cbc33/source/index.js#L369):  https://github.com/storyblok/storyblok-js-client/blob/e337bbbc936988a6e65d5c21da9df4adb20cbc33/source/index.js#L260 

Thanks for your help!

**Comment by VojislavVlasic** [comment]
Hi @Schinkentanz, thank you for letting us know.
What's the version that works ok for you?

**Comment by Schinkentanz** [comment]
Hey @VojislavVlasic the version it works with is `v4.3.1`

**Comment by VojislavVlasic** [comment]
Thank you for that as well.
I'll talk to the team and I'll let you know if we need any more info.

**Comment by Schinkentanz** [comment]
Thanks for that @VojislavVlasic 😄

**Comment by thiagosaife** [comment]
Hello @Schinkentanz 

Thanks for pointing this out. I've just opened a pull request to solve this issue.
Thanks a lot!

**Comment by thiagosaife** [comment]
@Schinkentanz Please get the version [4.5.4](https://github.com/storyblok/storyblok-js-client/releases/tag/v4.5.4) and try fetching the data again.

**Comment by Schinkentanz** [comment]
Hey @thiagosaife thanks! It works again 👍

**Comment by thiagosaife** [comment]
@Schinkentanz Thanks for the update.
