### ISSUE TITLE
importing a component containing `StoryblokComponent` from an external library results in an error

### ISSUE THREAD

**Issue by blindfish3** [storyblok/storyblok-js-client#224]
I'm working on a Svelte component library that includes components for use with Storyblok.  These components work fine when imported directly from within my main project; but I get an error when I try to import them from the library.  I've been able to establish that this is related to the use of `<StoryblokComponent>` within the library components; but so far have been unable to debug further.

I've set up a repo that demonstrates the problem: https://github.com/blindfish3/storyblok-error-repro
README.md contains some more detail of the error and how to reproduce it.

I'm fairly new to Storyblok and Sveltekit; so it's perfectly possible I've made a simple mistake; but I'm confused by the fact everything works fine with local imports; but not when importing from the library...

**Comment by blindfish3** [comment]
I've just figured out the cause of the problem; but not yet sure of a solution.
I edited ./node_modules/@storyblok/svelte/index.ts in both my-app and my-library and added a console.log in the getComponent() function - making sure to add a distinguishing label to each; and to output the value of componentsMap.
This confirmed that the components imported from the library are (obviously!) importing storyblok from their local node_modules; so componentsMap is null.

So `storyblokInit` needs to have a global location in which to store componentsMap; otherwise we can't work with imported components from a shared library :cry:

**Comment by blindfish3** [comment]
One possible solution:
In your application create an alias to '@storyblok/svelte' pointing to './node_modules/@storyblok/svelte'.  This means any imported module will use the local version of storyblok (rather than from their node_modules folder) and this resolves the issue.

For more info on the problem and possible solutions see [npm link, peerDependencies and webpack](https://penx.medium.com/managing-dependencies-in-a-node-package-so-that-they-are-compatible-with-npm-link-61befa5aaca7).

It might be helpful to document this issue and the solution: I don't think it's an uncommon requirement to want to package Storyblok components into a shared library; and I don't think it's unusual to use npm link during library development.

**Comment by josefineschaefer** [comment]
Thank you so much for your feedback and for raising this issue. I will have a look at what you described and see how we can make this more clear or resolve. It might take a couple of days but I'll get back to you as soon as I know more. Sorry for the incovenience.

**Comment by blindfish3** [comment]
Thanks for the reply.  TBH this feels like a bit of an edge case! It's just one that will probably crop up more often in this context; since setting up a library of components to work with Storyblok is likely to be a common requirement ;)

In terms of the solution, it looks like the simplest option is to add the alias to svelte.config.js:

```js
	kit: {
	        // any module importing @storyblok/svelte will get it from the aliased location
		alias: {
			'@storyblok/svelte': './node_modules/@storyblok/svelte'
		},
```
This ensures that the `storyblokApiInstance` and `componentsMap` stored when Storyblok is initialised are available to components from the library.  The only risk that I can see here is if the library and project have dependencies on different versions of @storyblok/svelte; but that seems unlikely...

**Comment by josefineschaefer** [comment]
Resolved by [docs(readme): add section on aliases #98](https://github.com/storyblok/storyblok-svelte/pull/98 )
