### ISSUE TITLE
Error on build - core-js/modules/es.function.name in ./node_modules/storyblok-js-client/dist/throttlePromise.js 

### ISSUE THREAD

**Issue by jajouka79** [storyblok/storyblok-js-client#23]
This dependency was not found: friendly-errors 12:06:24
* core-js/modules/es.function.name in ./node_modules/storyblok-js-client/dist/throttlePromise.js 

I am getting this error when trying to build. I have tried adding a newer version of the babel corjs dependency in the project to override the sb js client dep:

yarn add @babel/runtime-corejs3 --dev

still getting the same error

**Comment by DominikAngerer** [comment]
Hey there!

Can you share the full error log with us? Also can you check this:

```
This dependency was not found: friendly-errors 12:06:24
```

Which node, npm and yarn version are you using?

**Comment by aerophobic** [comment]
@jajouka79 installing the runtime-corejs3 doesn't fix it completely - you need to install core-js@3 aswell - give it a try:
`yarn add -D core-js@3 @babel/runtime-corejs3`
can you confirm this @DominikAngerer ? if i assume correctly and you are using nuxt/next, don't forget to adjust the nuxt/next.config.js to match the core-js version (in the build prop).

**Comment by onefriendaday** [comment]
Thanks for the bug report!
The error of
`core-js/modules/es.function.name in ./node_modules/storyblok-js-client/dist/throttlePromise.js`
has been fixed in version 1.0.30
