### ISSUE TITLE
Ts declaration adjustment

### ISSUE THREAD

**Issue by eduardluft** [storyblok/storyblok-js-client#248]
Heyo,

we have embedded the storyblok js client via typescript and everything is working :)

But we noticed a little inaccuracy in the interface StoryblokResult defined in index.d.ts.

```
export interface StoryblokResult {
  data: any
  perPage: number
  total: number
  headers: any
}
```

The properties `perPage` & `total` are `undefined` if `res.headers["per-page"]` is not given.
See condition in: https://github.com/storyblok/storyblok-js-client/blob/c0a13a3845905ab6f188eaa6331df2dcd269cfb3/source/index.js#L407

Therefore a suggestion to declare these values as nullable for example in order to not encounter unexpected / undefined values if using typescript.

Regards

**Comment by thiagosaife** [comment]
Hello @eduardluft . Makes sense. We'll take a look into this. Thanks for pointing this out. @VojislavVlasic

**Comment by VojislavVlasic** [comment]
Hello @eduardluft, this was taken care of, please let us know if you have any further comments.
Thank you for your help!
