### ISSUE TITLE
TypeScript: setComponentResolver lacks return-type annotation

### ISSUE THREAD

**Issue by MarvinRudolph** [storyblok/storyblok-js-client#25]
Hey! 

I use storyblok with nuxt and VSCode complains about the `setComponentResolver` in `index.d.ts`.
Error is `'setComponentResolver', which lacks return-type annotation, implicitly has an 'any' return type.`.

Is there a way to fix this or is it a wrong definition?

Thank you! :)

**Comment by onefriendaday** [comment]
Hi!

Following the place where this is defined:  
https://github.com/storyblok/storyblok-js-client/blob/master/dist/index.d.ts#L162

Could you make a PR or give a hint?

**Comment by MarvinRudolph** [comment]
> Hi!
> 
> Following the place where this is defined:
> https://github.com/storyblok/storyblok-js-client/blob/master/dist/index.d.ts#L162
> 
> Could you make a PR or give a hint?

Oh sorry the master is version 2 and the definition there is a bit different.
I am using `storyblok-nuxt` and the version there is `1.0.12` so that might be the problem.

Is there a way to use the current version for `storyblok-nuxt`? :)

**Comment by onefriendaday** [comment]
I see, thanks for checking.

We updated the v1 (storyblok-js-client@1.0.33) so that storyblok-nuxt uses the right ts definition.

storyblok-nuxt isn't outdated. The difference between v1 and v2 is that v2 uses corejs 3
