### ISSUE TITLE
getAll typings currently missing

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok-js-client#28]
Hi,
I was trying out the new release of the js-client today and thought the getAll method will be very handy. But I think the dist folder and the typings haven't been updated yet?
Thanks!

**Comment by onefriendaday** [comment]
Has been fixed in 2.0.8

**Comment by dohomi** [comment]
@onefriendaday thanks looking great. One question though: is there a reason why the `getAll` call does not respect the cache mechanism? It might be great to enable/disable the caching for the getAll call as well?
