### ISSUE TITLE
TS definition for client.get doesn't allow to get datasources

### ISSUE THREAD

**Issue by snk7891** [storyblok/storyblok-js-client#297]
Currently the following code is raising a TS error:

```
const { data } = client.get('cdn/datasource_entries', {
  datasource: 'labels',
  cv,
});
```

The error is:
```
 error TS2345: Argument of type '{ datasource: string; dimension: Language; cv: any; }' is not assignable to parameter of type 'ISbStoriesParams'.
  Object literal may only specify known properties, and 'datasource' does not exist in type 'ISbStoriesParams'.
```

I resolved by extending the IsbStoriesInterface, but I assume this should be covered within the library

**Comment by thiagosaife** [comment]
Hi @snk7891 I'll get into this. Thanks for the update.

**Comment by snk7891** [comment]
Thank you very much for the good news and the suggestion, will adjust it asap.

I think this can be closed now :)
