### ISSUE TITLE
Client does not send API requests

### ISSUE THREAD

**Issue by danielxbauer** [storyblok/storyblok-js-client#298]
In the current version (v5.0.0), no API call is sent when `getStories` is called and an empty object (`{}`) is returned instead.

**Steps to reproduce**
```ts
const sbClient = new StoryblokClient({
  accessToken: '<TOKEN>'
});

sbClient.getStories({ }).then((s) => console.log(s));
```

The console logs an empty object `{}`.

**Fix**
After debugging the source code I noticed that the default cache provider implementation is incorrect as it always returns an empty object instead of `undefined`. This will never send an API request, since it assumes this empty object is a valid cached one and returns this instead.

Current implementation `src/index.ts` Line 525:
```ts
get() {
	return {} as IMemoryType // NOTE: This should return undefined!
},
getAll() {
	return {} as IMemoryType // NOTE: This should return undefined!
},
set() {
	return {} // NOTE: This line could be removed as a void method is expected
},
flush() {
	return {} // NOTE: This line could be removed as a void method is expected
},
```

The updated (and working) implementation should be:
```ts
get() {
  return undefined;
},
getAll() {
  return undefined;
},
set() {},
flush() {},
```

**Comment by danielxbauer** [comment]
I can make a pull request if desired.

**Comment by thiagosaife** [comment]
Hi @danielxbauer . Please try again with the new version 5.0.2. We just fixed this issue. Thanks for your help on this.

**Comment by thiagosaife** [comment]
I will close this issue, but feel free to reopen it if this problem persists.

**Comment by danielxbauer** [comment]
@thiagosaife Thanks for the quick fix. It works now as intended. 🚀👏🏻
