### ISSUE TITLE
Caching issue not resolved and not documented but closed. 

### ISSUE THREAD

**Issue by RobIsHere** [storyblok/storyblok-js-client#35]
We puzzle about cache issues since day 1. We cannot use the webhook but must use polling for new cache versions.
Although upgrading to 2.0.10 did solve an error crashing our refresh-timer, the customer is still reporting caching issues more often than once a day!!

The caching of cdn/spaces/me must be considered a BUG if not documented properly. Because the documentation says explicitly: use this to get the new cache-version! No one would expect such a request to get cached inside the client.

Closing this issue without action has cost us about three days searching errors
https://github.com/storyblok/storyblok-js-client/issues/10

I'll update the code now and hope this has been the last caching issue.

**Comment by onefriendaday** [comment]
We added a check to bypass the cache if spaces/me is called in v2.0.12.
