### ISSUE TITLE
Property 'addComments' does not exist on type 'StoryblokBridge'

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok-js-client#41]
Hello

I try to use `window.storyblok.addComments(event.story.content, event.story.id)` with TypeScript but it does not seem to be type safe. I'm not sure if I miss something on my side?
Thanks

**Comment by emanuelgsouza** [comment]
Hi! Thanks for submitting this issue.

This definition type was included on [v2.2.0](https://github.com/storyblok/storyblok-js-client/releases/tag/v2.2.0)
