### ISSUE TITLE
resolveNestedRelations is not working

### ISSUE THREAD

**Issue by marco-primoza** [storyblok/storyblok-js-client#416]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client

[![storyblok.com](https://a.storyblok.com/f/88751/1776x360/4d075611c6/sb-js-sdk.png)][storyblokurl]

The configuration option `resolveNestedRelations` does not have any effect—nested relations are never resolved.

---

## Expected Behavior

If `resolveNestedRelations: true` is included in the configuration, nested relations should be resolved.

## Current Behavior

Even if `resolveNestedRelations: true` is included in the configuration, nested relations are not resolved.

Currently the value in the configuration object is not used and `this.resolveNestedRelations` is always set to `false`:
https://github.com/storyblok/storyblok-js-client/blob/50e0c017e7966506dc45359a3edf5a7340223865/src/index.ts#L143  

---

It's probably an easy fix:
```ts
this.resolveNestedRelations = config.resolveNestedRelations
```

In the meantime if someone else is running into that problem, you can just set `resolveNestedRelations` after initializing the client.

```ts
const Storyblok = new StoryblokClient({
  accessToken: <YOUR_SPACE_ACCESS_TOKEN>,
});
Storyblok.resolveNestedRelations = true;
```

**Comment by dohomi** [comment]
I experience the same issue, thanks @marco-primoza for your solutions this works for now

**Comment by kevbook** [comment]
Not sure if this is working for me. Any help would be appreciated. My GET request has the this query string `resolve_relations=markets`

```json
{
  "data": {
    "story": {
      "name": "Markets",
      "uuid": "52829ede-1d14-4d30-8180-8170ef713126",
      "content": {
        "markets": [
          "72d614cb-0459-40d9-9ca9-f57864ff2185",
          "ee11a9ab-057b-47c6-bbf5-1183a682ef1e"
        ]
      }
    },
    "rels": [
      {
        "name": "Atlanta",
        "uuid": "72d614cb-0459-40d9-9ca9-f57864ff2185",
        "content": { }
      },
      {
        "name": "Jacksonville",
        "uuid": "ee11a9ab-057b-47c6-bbf5-1183a682ef1e",
        "content": { }
      }
    ]
  }
}
```

**Comment by marco-primoza** [comment]
@thiagosaife I'm not sure if @kevbook's issue is related to this one.
Maybe it would make sense to discuss this in a dedicated issue?

Also: Do you want me to open a pull request for this?

**Comment by petr166** [comment]
I'm experiencing the same issue as @kevbook; `story.content` is not populated with the resolved relations. Now I'm not sure this is an issue with the client or the SB api, as the [api docs](https://www.storyblok.com/docs/api/content-delivery/v2#examples/useful/resolve-relationships) show resolved relations (populated in `content`) even for the curl request. 

Let me know if it's within the scope of this client or we should look for help elsewhere.

e.g. response for `https://api.storyblok.com/v2/cdn/stories/test-relations?resolve_relations=testers&token=asdf`

```json
{
    "story": {
        "name": "Test Relations",
        "created_at": "2023-03-17T09:01:37.070Z",
        "published_at": "2023-03-17T10:14:33.006Z",
        "id": 277446141,
        "uuid": "f752b2f0-9b06-4767-9329-ecaed7319272",
        "content": {
            "_uid": "030d13e9-56dc-4e66-9891-b516f489b23d",
            "testers": [
                "a3e8b0f6-4e5a-4025-9c4e-e96ab23fc5b0"
            ],
            "component": "root"
        },
        "slug": "test-relations",
        "full_slug": "test-relations",
    },
    "cv": 1679048073,
    "rels": [
        {
            "name": "Tester Test",
            "created_at": "2023-03-17T10:13:56.963Z",
            "published_at": "2023-03-17T10:14:14.242Z",
            "id": 277570555,
            "uuid": "a3e8b0f6-4e5a-4025-9c4e-e96ab23fc5b0",
            "content": {
                "_uid": "4d034073-e675-4c07-8345-eef53332da8f",
                "name": "Tester Test",
                "title": "Tester",
                "component": "Churner",
                "description": ""
            },
            "slug": "tester-test",
            "full_slug": "team/tester-test",
        }
    ],
    "links": []
}
```

**Comment by petr166** [comment]
any news on this @thiagosaife?

**Comment by ademarCardoso** [comment]
This problem should have been resolved in version [5.9.0](https://github.com/storyblok/storyblok-js-client/releases/tag/v5.9.0), does it still persist? 

With which version did you test? @petr166

**Comment by petr166** [comment]
Hi @ademarCardoso 👋!

Just tested on `storyblok-js-client@5.10.2` (dependency of `@storyblok/react@2.0.18` i'm using) and it's not fixed. 
It might be that we're not talking about the same issue though, as the release you shared seems to fix `resolveNestedRelations` prop, i'm not sure that's controlling the faulty behaviour me and @kevbook have. 

In fact, could you maybe clarify for us if `resolveNestedRelations` affects top level relations like i have in my e.g. https://github.com/storyblok/storyblok-js-client/issues/416#issuecomment-1473621018? Otherwise it might be wise for me to open another issue i guess.

**Comment by roberto-butti** [comment]
> I'm experiencing the same issue as @kevbook; `story.content` is not populated with the resolved relations. Now I'm not sure this is an issue with the client or the SB api, as the [api docs](https://www.storyblok.com/docs/api/content-delivery/v2#examples/useful/resolve-relationships) show resolved relations (populated in `content`) even for the curl request.
> 
> Let me know if it's within the scope of this client or we should look for help elsewhere.
> 
> e.g. response for `https://api.storyblok.com/v2/cdn/stories/test-relations?resolve_relations=testers&token=asdf`
> 
> ```json
> {
>     "story": {
>         "name": "Test Relations",
>         "created_at": "2023-03-17T09:01:37.070Z",
>         "published_at": "2023-03-17T10:14:33.006Z",
>         "id": 277446141,
>         "uuid": "f752b2f0-9b06-4767-9329-ecaed7319272",
>         "content": {
>             "_uid": "030d13e9-56dc-4e66-9891-b516f489b23d",
>             "testers": [
>                 "a3e8b0f6-4e5a-4025-9c4e-e96ab23fc5b0"
>             ],
>             "component": "root"
>         },
>         "slug": "test-relations",
>         "full_slug": "test-relations",
>     },
>     "cv": 1679048073,
>     "rels": [
>         {
>             "name": "Tester Test",
>             "created_at": "2023-03-17T10:13:56.963Z",
>             "published_at": "2023-03-17T10:14:14.242Z",
>             "id": 277570555,
>             "uuid": "a3e8b0f6-4e5a-4025-9c4e-e96ab23fc5b0",
>             "content": {
>                 "_uid": "4d034073-e675-4c07-8345-eef53332da8f",
>                 "name": "Tester Test",
>                 "title": "Tester",
>                 "component": "Churner",
>                 "description": ""
>             },
>             "slug": "tester-test",
>             "full_slug": "team/tester-test",
>         }
>     ],
>     "links": []
> }
> ```

Hi @petr166 , for resolving relations, you need to use the " extended" syntax with the component name and the field name.
According to: https://www.storyblok.com/tp/using-relationship-resolving-to-include-other-content-entries#retrieving-the-content-via-get-method.
```
the resolve_relations option: set with the name of the block name (featured_posts) and the field name (posts), for example, featured_posts.posts.
```
In your case, checking your json response, i would try to set root.testers.

Let me give you another example.
Following the API doc: https://www.storyblok.com/docs/api/content-delivery/v2#examples/useful/resolve-relationships in the API call, the `resolve_relations=categories` is used. For filling the rels attribute and for the API call, it is fine. For SDK, if you want also instruct the SDK to copy the resolved story from `rels` , into the right place of the JSON structure, you need to use the full form like `post.categories`

If you want to understand more, try to execute the following two scripts (the only difference is the resolve_relations):
```
import StoryblokClient from "storyblok-js-client";
const Storyblok = new StoryblokClient({
    accessToken: 'ask9soUkv02QqbZgmZdeDAtt',
});
let response = await Storyblok.get('cdn/stories', {
    version: 'draft',
    starts_with:'posts',
    resolve_relations: 'categories',
})
```

and

```
import StoryblokClient from "storyblok-js-client";
const Storyblok = new StoryblokClient({
    accessToken: 'ask9soUkv02QqbZgmZdeDAtt',
});
let response = await Storyblok.get('cdn/stories', {
    version: 'draft',
    starts_with:'posts',
    resolve_relations: 'post.categories',
})
```

Let me know if this helps you.

**Comment by petr166** [comment]
@roberto-butti it works, thanks a lot. I could swear I've tried every variant of the object path, but maybe not the most obvious one 😅
