### ISSUE TITLE
TS2322: sbFetch: Type 'Headers | undefined[]' is not assignable to type 'Headers'.

### ISSUE THREAD

**Issue by webtsofficial** [storyblok/storyblok-js-client#436]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client

[![storyblok.com](https://a.storyblok.com/f/88751/1776x360/4d075611c6/sb-js-sdk.png)][storyblokurl]

## Expected Behavior

Typescript should not fail at compilation

## Current Behavior

Typescript fails at compilation with the message:
```bash
error TS2322: Type 'Headers | undefined[]' is not assignable to type 'Headers'.
  Type 'undefined[]' is missing the following properties from type 'Headers': append, delete, get, has, set
```

## Steps to Reproduce

I use the client inside a basic angular 15 universal app with the following `tsconfig.json`:
```
{
    "compileOnSave": false,
    "compilerOptions": {
        "baseUrl": "./",
        "outDir": "./dist/out-tsc",
        "strict": false,
        "strictNullChecks": false,
        "downlevelIteration": true,
        "experimentalDecorators": true,
        "moduleResolution": "node",
        "target": "ES2022",
        "module": "ES2022",
        "lib": [
            "ES2022",
            "dom",
            "dom.iterable" // <-- this is also necessary for the lib to compile?
        ]
    },
    "angularCompilerOptions": {
        ...
    }
}
```

package.json:
```json
{
  "name": "test-project",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "dev:ssr": "ng run test-project:serve-ssr",
    "serve:ssr": "node dist/test-project/server/main.js",
    "build:ssr": "ng build && ng run test-project:server",
    "prerender": "ng run test-project:prerender"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^15.1.0",
    "@angular/common": "^15.1.0",
    "@angular/compiler": "^15.1.0",
    "@angular/core": "^15.1.0",
    "@angular/forms": "^15.1.0",
    "@angular/platform-browser": "^15.1.0",
    "@angular/platform-browser-dynamic": "^15.1.0",
    "@angular/platform-server": "^15.1.0",
    "@angular/router": "^15.1.0",
    "@nguniversal/express-engine": "^15.1.0",
    "express": "^4.15.2",
    "ng-dynamic-component": "^10.6.1",
    "rxjs": "~7.8.0",
    "storyblok-js-client": "^5.3.6",
    "tslib": "^2.3.0",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.1.3",
    "@angular/cli": "~15.1.3",
    "@angular/compiler-cli": "^15.1.0",
    "@nguniversal/builders": "^15.1.0",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~4.3.0",
    "@types/node": "^14.15.0",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "ng-packagr": "^15.1.0",
    "typescript": "~4.9.4"
  }
}
```

1. create a @angular/cli project (`ng new project-name`)
2. `cd project-name`
3. `ng add @nguniversal/express-engine`
4. `npm i storyblok-js-client --save`
5. use the `Client` inside a service like described in the [Storyblok Article](https://www.storyblok.com/tp/add-a-headless-cms-to-angular-in-5-minutes)
6. run `npm run dev:ssr`

## Steps to Fix

In the `src/sbFetch.ts` change the default value passed to the header property from `[]` to `new Headers()` like in the following:
**From**
```typescript
public constructor($c: ISbFetch) {
    this.headers = $c.headers || []
    // ...
}
```
**To**
```typescript
public constructor($c: ISbFetch) {
    this.headers = $c.headers || new Headers()
    // ...
}
```

## Extras
It could be a mistake I made while implementing it, but not sure if a library should have compile time errors for typescript (I saw you are using esnext and also yout typescript version is not too far off `"typescript": "^4.8.4",`- but couldn't see something that spoke for the ecma script or typescript version mismatch in the tsconfig / package.json while trying to resolve the error without editing files in the node modules directory)

**Comment by zwaldeck** [comment]
I have the same problem.

I reverted the **storyblok-js-client** to version **5.1.6**

There I don't have this problem, but it would be nice to be able to use the latest version of the client
