### ISSUE TITLE
Caching functionality not working

### ISSUE THREAD

**Issue by tristan-mastrodicasa** [storyblok/storyblok-js-client#47]
I have this configuration

```javascript
sbClient = new storyblokJsClient({
  accessToken: 'dsasdfgaadfgadfgadfg',
  cache: { type: 'memory', clear: 'auto' },
});
```

```javascript
sbClient.getStory(slug, params).then(res => res.data);
```

In google dev tools the stories do not seem to be retrieved from the cache.

I noticed that the "cacheVersion" (the cv in the URL) in the URL kept updating with a new timestamp...

`https://api.storyblok.com/v1/cdn/stories/index?version=published&cv=1586954854930`
`https://api.storyblok.com/v1/cdn/stories/index?version=published&cv=1586955269827`

Is there something going on here? How do I stop the cv from changing?

**Comment by emanuelgsouza** [comment]
Hi, thanks for submitting your issue!

Could you please share with us how to you are making the request? It is possible that you are reinstating the Storyblok class before making a request. Therefore, at each instance a new version of cache is generated.

**Comment by tristan-mastrodicasa** [comment]
After checking my code it seems the class is being reinstated
