### ISSUE TITLE
Issue with constructor in typescript ?

### ISSUE THREAD

**Issue by marckraw** [storyblok/storyblok-js-client#50]
Hi i have a weird issue. I was trying to use `storyblok-js-client` inside typescript project, with that code
```
import storyblokConfig from '../config/config'
import StoryblokClient from 'storyblok-js-client'

const { accessToken, oauthToken, storyblokApiUrl } = storyblokConfig
export let sbApi = new StoryblokClient({ accessToken, oauthToken }, storyblokApiUrl)
```

Inside `storyblokConfig` i have all the config variables i need to properly create `StoryblokClient` object.

But in terminal, error happens:
```
(node:15460) TypeError Plugin: sb-mig: storyblok_js_client_1.default is not a constructor
```

Rigth now, my workaround is to "**require**" `storyblok-js-client`, but also to import types from `storyblok-js-client` normally.

Also, maybe i'm doing something horrible wrong here with typescript + storyblok-js-client, so let me know :)

**Comment by marckraw** [comment]
Also related probably, i've found that there is missing type inside `index.d.ts`

![image](https://user-images.githubusercontent.com/8228270/80697070-b60b8a00-8ad8-11ea-8d54-cff151364ed7.png)
![image](https://user-images.githubusercontent.com/8228270/80697087-bb68d480-8ad8-11ea-8c0a-d89ea58aff96.png)

**Comment by emanuelgsouza** [comment]
Hi, thanks for submitting this issue. The last version of [storyblok-js-client (2.4.1) fixes this](https://github.com/storyblok/storyblok-js-client/releases/tag/v2.4.1). Check out!

**Comment by blakekrammes** [comment]
I still have this issue with 2.4.1.

**Comment by emanuelgsouza** [comment]
Hi @blakekrammes ! What's happening?

**Comment by blakekrammes** [comment]
Hey @emanuelgsouza,

The same error that @marckraw mentioned above when using an import instead of require:

<img width="1678" alt="Screen Shot 2020-05-18 at 2 57 29 PM" src="https://user-images.githubusercontent.com/49688912/82254184-00ce3400-9918-11ea-8249-e773c01655e8.png">

**Comment by emanuelgsouza** [comment]
How are you import and instantiate the package? Could you share with us the `storyblok.service.js` file? Is this an open source project?

**Comment by blakekrammes** [comment]
Sure. I'm not too concerned about just using require here, but it would be nice to use import and that you all might want to know. 

```typescript
import { Injectable } from '@nestjs/common';
import { ConfigService } from 'src/core/config/config.service';
import StoryblokClient from 'storyblok-js-client';
// eslint-disable-next-line @typescript-eslint/no-var-requires
// const StoryblokClient = require('storyblok-js-client');

@Injectable()
export class StoryblokService {
  token = '';
  sb: any;

  constructor(private readonly config: ConfigService) {
    this.token = this.config.STORYBLOK_TOKEN;
    this.sb = new StoryblokClient({
      accessToken: this.token,
      cache: {
        clear: 'auto',
        type: 'memory',
      },
    });
  }

  async getStory(): Promise<boolean> {
    try {
      const result = await this.sb.get(
        'cdn/stories/...',
        {
          version: 'draft',
        },
      );

      const contentObj = result;
      const content = JSON.stringify(contentObj);
      console.log(content);
    } catch (e) {
      console.log(e);
    }

    return true;
  }
}

```

**Comment by emanuelgsouza** [comment]
Hi, I'm investigating here and, like I saw in your code, you're using Typescript. So, I believe the problem is in Typescript config. The `storyblok-js-client` uses CommonJS, and, Typescript, like default, uses the AMD.

Investigating, I found the TS documentation about Module Resolutions. The default is `Classic`, but, in my tests, the `Node` option works (because the final code will test if the module uses EsModules or CommonJS).

The tsconfig.json I used on my tests was:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "target": "es6",
    "moduleResolution": "node"
  }
}
```

The documentation about [Module Resolutions](https://www.typescriptlang.org/docs/handbook/module-resolution.html)

**Comment by oytuntez** [comment]
I was just writing a migration script via this SDK and encountered the same issue. I had to revert `module: "esnext"` to `module: "commonjs"` for the constructor to work (using ts-node).

**Comment by emanuelgsouza** [comment]
Hi everyone!

Thanks for this discussion. We released a [v3.1.0](https://github.com/storyblok/storyblok-js-client/releases/tag/v3.1.0) version with some improvements in our code, especially related to the integration with Typescript and a decrease of the final bundle.

Check out!

**Comment by imabp** [comment]
Is this issue still existing? I am unable to reproduce it.

**Comment by marcinkrawczyk-ef** [comment]
me the same, i think we can close that :)

**Comment by marckraw** [comment]
me the same, i think we can close that :)

**Comment by imabp** [comment]
Also @marckraw can you check out #139 , its related to Typescript again.
