### ISSUE TITLE
.post() method return type mismatched

### ISSUE THREAD

**Issue by Chrisissorry** [storyblok/storyblok-js-client#518]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

---

## Expected Behavior

When I send a post request with `storyblokClient.post()`, I expect to receive an object that implements the `ISbResponseData` interface. The `ISbResponseData` interface is defined and exported properly from the `interfaces.ts` file.

## Current Behavior

`.post()` returns an object that looks like a mixture of`ISbResponse` and `ISbManagmentApiResult` rather than a `ISbResponseData` object. 

## Steps to Reproduce

1. Install the `storyblok-js-client` and configure it properly
2. Instantiate the client and make a post request to the SB Management API, i.e. create a story
3. Check the returned data

**Comment by andriik-brights** [comment]
@thiagosaife  Hi, do you know if it was merged? thanks

**Comment by nx-rupalisoni** [comment]
@thiagosaife, Do you have any update for this issue?

**Comment by andriik-brights** [comment]
hi, @thiagosaife . do you if there any updates?

**Comment by andriik-brights** [comment]
@thiagosaife hi. i saw you just releasesd a new version 6.0.0. should it be fixed in this version ? (i've just tryied  works the same )

**Comment by alvarosabu** [comment]
I will close this due inactivity, feel free to re-open if it's still relevant

**Comment by fmaerkl-sw** [comment]
> We made all the changes related to this matter.

Which changes are you referring to? Is it https://github.com/storyblok/storyblok-js-client/pull/676? Will this be merged later?

> However it would be a breaking change, so we'll release this solution with our next major release.

This comment was made quite a while ago now. What version number would be the next major release in this context? 7.0.0?
