### ISSUE TITLE
Unable to find documentation for adding, deleting, and assigning tags to images using Storyblok Management API

### ISSUE THREAD

**Issue by pshata** [storyblok/storyblok-js-client#521]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

I am currently facing an issue with finding documentation on how to add, delete, and assign tags to images using the Storyblok Management API. Despite my extensive search, I have not been able to find any relevant information on this matter.

Could you please provide me with the necessary documentation or information on how to achieve this functionality using the Storyblok Management API? I need to automate this process for my project and any help in this regard would be greatly appreciated.

Thank you.

**Comment by VojislavVlasic** [comment]
Hi @pshata!
This is a repo for JS client.
If you need help with our MAPI and the documentation, please reach out to our customer support or go to our Discord community.
