### ISSUE TITLE
Is there an import to the export described?

### ISSUE THREAD

**Issue by ThornWalli** [storyblok/storyblok-js-client#527]
Hello,

I have a question about this topic: https://github.com/storyblok/storyblok-js-client#download-all-content-from-storyblok

An export is described here, is there also an import for this?

Thanks! 🙂

**Comment by VojislavVlasic** [comment]
Hi @ThornWalli,
Hope you're doing well.
For support please check out our Discord Community or reach out to our Help Desk.
Have a wonderful day.
