### ISSUE TITLE
Storyblok Bridge is not being initialized

### ISSUE THREAD

**Issue by eduardfossas** [storyblok/storyblok-js-client#537]
Hello, I am using Next.js with Storyblok-js-client and I remember before Storyblok bridge was automatically available in the window object. Do I need to add something else to make it work?

Thank you and warm regards.

**Comment by VojislavVlasic** [comment]
Hi @eduardfossas,
Hope you're doing well.
For support please check out our Discord Community or reach out to our Help Desk.
Have a wonderful day.
