### ISSUE TITLE
RichText Formatting from clipboard breaks TipTap color

### ISSUE THREAD

**Issue by markus-gx** [storyblok/storyblok-js-client#543]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

From Discord, several users have raised an issue with the RichText Editor

Seems like pasting a text that has color formatted breaks the editor

<img width="1379" alt="CleanShot_2023-04-23_at_16 53 032x" src="https://user-images.githubusercontent.com/4699008/234586994-5f6db2b9-1f51-48b4-8ea6-8f2de4701854.png">

![CleanShot_2023-04-23_at_16 54 112x](https://user-images.githubusercontent.com/4699008/234587205-27ebf112-fbe8-495f-95cd-ac7968a386f2.png)

> It's caused by the attr.color in the API response being undefined on the storyblok api response for rich text fields elements e.g. a heading or paragraph.

## Expected Behavior

Shouldn't break the TipTap editor.

## Current Behavior

Breaks the editor even if no text-highlight color is selected.

## Steps to Reproduce

1. Open Rich Text Field on editor
2. Add a color tag with no hex code or copy some text with color formatting
3. See error

**Comment by samducker** [comment]
That looks good to me, I reported it using Astro (another also reported on Vue however. So assume it is not related specifically to the Astro SDK). Doesn't occur if there is no colour inside a rich text, just if the hex code is undefined. Seems to happen on various tags within rich text e.g. paragraph or heading.

**Comment by ademarCardoso** [comment]
Thank you for reporting, I will look into this problem and resolve it as soon as possible 😄

**Comment by markus-gx** [comment]
> Thank you for reporting, I will look into this problem and resolve it as soon as possible 😄 
> 
> 
> 
> But one question this happens only inside the richtext in the editor ? Or using the resolver in the js-client too ?
> 
> 
> 
> cc: @markus-gx @samducker @alvarosabu 

in the js-client for me :)

**Comment by samducker** [comment]
I think the problem resides in the editor allowing you to pass undefined values and the js-client not handling the undefined case.

**Comment by ademarCardoso** [comment]
Hello guys, I'm trying to reproduce and I'm not able to reproduce 100%, could you send me a video ?, without sensitive data.
If you prefer to send me via discord, I'm on the storyblok discord `Ademar#7949`

cc: @samducker @markus-gx

**Comment by SebbeJohansson** [comment]
@ademarCardoso the nuxt2 module is also having this issue now after a bugfix version of the js client was released. Noticed it after upgrading on a test server and seeing that it suddenly didn't work compared to production.

Here is an example fetch: https://api.storyblok.com/v2/cdn/stories/campsite/how-to-waterproof-clothes?token=F20mFGXBEhpw61bIUtw1ZQtt

**Comment by SebbeJohansson** [comment]
I have made a workaround where I add an empty object as `attrs` to any mark that doesn't have `attrs`. You can look at it here: https://gist.github.com/SebbeJohansson/467244f90bec9e3e8994d4bacd00f794

**Comment by ademarCardoso** [comment]
My friend, could you take a look [at this PR](https://github.com/storyblok/storyblok-js-client/pull/561) and check if it solves the problem you are having?
I test with the data you sent and it worked for me.

cc: @SebbeJohansson

**Comment by SebbeJohansson** [comment]
Sorry, @alvarosabu this might sound stupid, but how do i test that PR? Just looking at it, it seems like it wouldn't fix the issue since the issue is inside mark code. Since its the `attrs` on the mark rather than the body that is undefined in the markdown.
You can see the specific part of the code here: https://gist.github.com/SebbeJohansson/467244f90bec9e3e8994d4bacd00f794#file-rich-text-helpers-js-L20

**Comment by ademarCardoso** [comment]
Hello my friend, I added some new handles, you can have a look, as I said before, I couldn't reproduce so I added test cases with missing or undefined attributes.

cc: @SebbeJohansson

**Comment by SebbeJohansson** [comment]
@ademarCardoso I think that would work! Im still not sure on how to test it locally!

Also noticed that I tagged Alvaro by mistake (gonna blame autocorrect on that one) earlier 😅

**Comment by ademarCardoso** [comment]
Nice, thanks for the help my friend @SebbeJohansson 😄 

@markus-gx Can you test and check if this solves the problem on your end?

I will ask other users to test it, and soon I will release this fix. Thanks in advance guys 😄

**Comment by markus-gx** [comment]
> Nice, thanks for the help my friend @SebbeJohansson 😄
> 
> @markus-gx Can you test and check if this solves the problem on your end?

Solves it on my end ;) Thanks.
