### ISSUE TITLE
Support resolve relations in bridge events

### ISSUE THREAD

**Issue by dsteinbach** [storyblok/storyblok-js-client#58]
I am listening for changes from the Storyblok editor (using storyblok-nuxt) but `event.story.content` does not contain resolved relations like my initial api request to storyblok has. What's the solution to this? I'd rather not run `window.location.reload()` on the input event. 
```
    this.$storybridge.on(['input', 'published', 'change'], (event) => {
      if (event.action == 'input') {
        if (event.story.id === this.story.id) {
          this.story.content = event.story.content
        }
      } else {
        window.location.reload()
      }
    })
```

Thanks!

**Comment by emanuelgsouza** [comment]
Hi, thanks for submit this issue. We fixed this problem (it was not related to storyblok-js-client itself, but, in our platform). You can check here: https://www.storyblok.com/cl/resolve-relations-with-storyblok-bridge
