### ISSUE TITLE
datasource_id and datasource_slug parameters are not available

### ISSUE THREAD

**Issue by johannes-lindgren** [storyblok/storyblok-js-client#586]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

When calling the `datasource_entries` endpoint in the management API with a `get` request, the `datasource_id` and `datasource_slug` are not available:

<img width="687" alt="image" src="https://github.com/storyblok/storyblok-js-client/assets/14206504/e245691b-4b29-4413-90c7-8c1465bc92cc">

---

## Expected Behavior

The ISbStoriesParams should contain properties for `datasource_id` and `datasource_slug`.

The client should append these as query parameters to the request.

## Current Behavior

I get a type error:

<img width="684" alt="image" src="https://github.com/storyblok/storyblok-js-client/assets/14206504/0da53f36-cafd-42cf-9e0e-864f3624c9e4">

Don't know if the request would fail or succeed.

## Steps to Reproduce

In a project with Typescript, instantiate a JS client

```ts
new StoryblokClient({
    oauthToken: `Bearer ${accessToken}`,
    region,
  })
```

Then make a get request

```ts
new StoryblokClient({
    oauthToken: `Bearer ${accessToken}`,
    region,
  })
    .get(`spaces/${spaceId.toString(10)}/datasource_entries`, {
      datasource_id: '1234',
      datasource_slug: 'my_ds',
    })
```

You will get type errors:

> TS2345: Argument of type '{ datasource_id: string; datasource_slug: string; }' is not assignable to parameter of type 'ISbStoriesParams'.   Object literal may only specify known properties, but 'datasource_id' does not exist in type 'ISbStoriesParams'. Did you mean to write 'datasource'?

> TS2345: Argument of type '{ datasource_slug: string; }' is not assignable to parameter of type 'ISbStoriesParams'.   Object literal may only specify known properties, but 'datasource_slug' does not exist in type 'ISbStoriesParams'. Did you mean to write 'datasource'?

**Comment by PranshuSrivastava** [comment]
Hey @johannes-lindgren I went through the ISbStoryParams interface in the src/interface.ts file. Just adding these 2 properties should be able to fix the problem. I would be willing to work on this if no one has taken it up yet.

**Comment by PranshuSrivastava** [comment]
Sure @thiagosaife, looking forward to it.
