### ISSUE TITLE
RichTextResolver does not render email links correctly

### ISSUE THREAD

**Issue by stefan-r** [storyblok/storyblok-js-client#62]
When using linktype `email` in storyblok cms the link is rendered without the `mailto:` protocol prefix in the (vue) client. The browser interprets the link as relative and so the current page path becomes the prefix for the resulting link.

**Comment by emanuelgsouza** [comment]
Hi, thanks for submitting this issue. Could you provide more information about that? Like a code snippet from your component; a Storyblok JSON (you can share a link with the preview token for the story).

**Comment by emanuelgsouza** [comment]
Hi @stefan-r , could you provide the JSON? Thanks
