### ISSUE TITLE
Lighten the dependencies

### ISSUE THREAD

**Issue by eyn** [storyblok/storyblok-js-client#63]
It would be great to lighten the dependencies of this package a bit - on the server side its not a problem but if doing queries on the client side then this adds >25Kb to the bundle size. It really feels like we should be able to get this down to 1-2kb as most of the bundle is axios, corejs, qs and @babel.

<img width="1210" alt="Screenshot 2020-09-03 at 15 24 04" src="https://user-images.githubusercontent.com/1094580/92127833-9b844d00-edf9-11ea-91e9-790292f5acf8.png">

Ideally we would be able to pass in a function that behaved like fetch to avoid polyfilling that too

**Comment by onefriendaday** [comment]
We have a beta release that solved your problem: https://github.com/storyblok/storyblok-js-client/releases/tag/v3.0.0-beta.1

Soon it will be released.

**Comment by eyn** [comment]
Thanks great news! We will try the beta release
