### ISSUE TITLE
[Next 13 - App Router] Support for on-demand revalidation by cache tag

### ISSUE THREAD

**Issue by standandmarvel** [storyblok/storyblok-js-client#652]
I'm looking for a way to revalidate Next.js data cache using the on-demand [revalidateTag method](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#on-demand-revalidation).
Is there an easy way to do this with the Storyblok API client?

---

## Expected Behavior

From what I understand, I essentially need to be able to add `{ next: { tags: ['collection'] }` to the Storyblok Client's fetch request.

I wondered if this might work if we had "fetchOptions" we could pass to the Storyblok Client, for example:

```js
const Storyblok = new StoryblokClient({
  accessToken: <YOUR_SPACE_ACCESS_TOKEN>,
  fetchOptions: { next: { tags: ['storyblok'] } } // <- Suggestion
})
```

Then in my Next.js application, I could a new 'revalidate' API route targeting my `storyblok` tagged data cache

```js
// app/api/revalidate/route.ts

import { NextRequest, NextResponse } from 'next/server'
import { revalidateTag } from 'next/cache'
 
export async function POST(request: NextRequest) {
   revalidateTag('storyblok')
 
  return NextResponse.json({ revalidated: true, now: Date.now() })
}
```

Finally, in my Storyblok Space settings, I could create a webhook that is triggered on publish/unpublish etc.
```
https://example.com/api/revalidate
```

Note that a similar approach is currently how Prismic recommends handling Data caching with the Next.js App Router [See Prismic docs](https://prismic.io/docs/fetch-data-nextjs#caching-with-the-app-router)

## Current Behavior

I couldn't find any documentation for on-demand revalidation of Next 13 data cache when working with the Storyblok API client.

**Comment by joakim-roos** [comment]
Hi, having the same challenge here. We're considering building our own Client for this as we haven't found a proper solution yet.

**Comment by mediabeastnz** [comment]
This can be closed as it's now possible to pass custom fetch options such as `cache: 'no-cache',`
