### ISSUE TITLE
3.0.0: Cannot resolve dependency 'storyblok-js-client'

### ISSUE THREAD

**Issue by wiledal** [storyblok/storyblok-js-client#66]
Was this version released prematurely?

`import Storyblok from 'storyblok-js-client` results in `Cannot resolve dependency 'storyblok-js-client'`

Using `parcel-bundler@1.12.4`

The examples for using it directly in-browser (https://cdn.jsdelivr.net/npm/storyblok-js-client@3.0.0/dist/index.standalone.js) gives you the jsdelivr error:
> Couldn't find the requested file /dist/index.standalone.js in storyblok-js-client. 

Reverting back to 2.5.2 resolves issues.

**Comment by emanuelgsouza** [comment]
Hi! Thanks for submitting this issue! Could you check again?

**Comment by wiledal** [comment]
Hey!

Using 3.0.1, `import Storyblok from 'storyblok-js-client'` now results in `/node_modules/storyblok-js-client/dist/index.es.js:6:44: Cannot resolve dependency 'axios'`

Again, using `parcel-bundler@1.12.4`.

Manually installing `axios` solved it.

Is this expected?

**Comment by emanuelgsouza** [comment]
Hey! It's expected. I will update the documentation about that.
