### ISSUE TITLE
v3.0.0 published without `dist` folder

### ISSUE THREAD

**Issue by mAAdhaTTah** [storyblok/storyblok-js-client#68]
Pretty self-explanatory: the `main` & `module` keys point to files in the `dist` folder, but they're not included in the published bundle:

![Screen Shot 2020-09-23 at 10 52 42 AM](https://user-images.githubusercontent.com/4371429/94029613-fb339f80-fd8a-11ea-81be-64d5995d28fe.jpg)

**Comment by emanuelgsouza** [comment]
hi! try to update the v3.1.0 version!

**Comment by mAAdhaTTah** [comment]
That seems to have resolved it. Thanks!
