### ISSUE TITLE
Storyblok client throttling crashing Astro adapter in CloudFlare Worker

### ISSUE THREAD

**Issue by Soviut** [storyblok/storyblok-js-client#682]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

I have a project using Astro. Astro has a CloudFlare Worker "adapter" for doing server side rendering (SSR). This will re-render the preview page every time someone hits "save" in the Storyblok editor.

However, after several consecutive saves, the worker eventually crashes, giving a "The script will never generate a response" error.

Based on the comment in this thread, it seems to be caused by throttling in the Storyblok client not resolving all its promises and therefore never returning a result. https://github.com/withastro/adapters/issues/43#issuecomment-1782206087

They include links to the code in question as well as some workaround code to monkey patch the Storyblok client.

---

## Expected Behavior

I should be able to save frequently without the Storyblok client failing.

## Current Behavior

Saving frequently causes the client to eventually fail, crashing the worker.

## Steps to Reproduce

The author of the original thread provided a Stackblitz to reproduce https://stackblitz.com/edit/github-tkyzda-4d7fjz?file=astro.config.mjs

1. Create an Astro project
2. Install the CloudFlare adapter for Astro
3. Follow this tutorial to create a `generateStaticPaths` function for Astro that calls Storyblok https://www.storyblok.com/tp/create-a-preview-environment-for-your-astro-website
4. Deploy to CloudFlare
5. Point Storyblok editor at cloudflare URL
6. Make content changes and save them quickly
7. Observe the cloudflare worker eventually return an error

**Comment by patrick-schneider-latori** [comment]
@thiagosaife Any updates on this one? We currently omit the client (and created our own fetcher), since it makes all our production sites crash...this should not be the case!

**Comment by Soviut** [comment]
@patrick-schneider-latori it would be good if you could post your solution or even make a PR with your changes.

**Comment by F0rce** [comment]
Is there any way to prioritise this? Like some other commenters, we have fallen down this rabbit hole and have not been able to sort it out, before finding this issue.

**Comment by negprof** [comment]
Also the same problem with this using hydrogen shopify.

**Comment by jansvabik** [comment]
I have to admit that I've been eagerly waiting for a solution to this problem for months, like many of you. Today, I decided to dive deeper into the code of both this repository and the [@storyblok/astro](https://github.com/storyblok/storyblok-astro) repository to see if I could contribute a solution myself. To my surprise, I discovered that we can adjust the `rateLimit` parameter in the `apiOptions` within our `astro.config.mjs` config. By default, [it's set to 5 requests](https://github.com/storyblok/storyblok-js-client/blob/5e29770c98c0013634a39b05b02c0aea6b260618/src/index.ts#L119), but adjusting it can significantly impact how the client behaves under heavy load. Here's a quick example of how you can adjust this in your config:

```js
// in your astro.config.mjs
// ...
storyblok({
    accessToken: env.STORYBLOK_TOKEN,
    apiOptions: {
        // ...
        rateLimit: 250,
        // ... 
    },
    // ...
})
// ...
```

I hope this solution helps others who are encountering the same issue. If anyone has further insights or alternative solutions, I encourage you to share them with the community. 🙂

**Comment by remi-freriks** [comment]
We have the same problem with Cloudflare Workers. Even with rateLimit at 250. Is Storyblok still working on this problem?

**Comment by alvarosabu** [comment]
Hi @remi-freriks let me discuss it internally.

**Comment by patrick-schneider-latori** [comment]
I really hope you find a final solution now @alvarosabu – this problem exists since months and your module is unusable for Cloudflare users.

**Comment by patrick-schneider-latori** [comment]
> @patrick-schneider-latori it would be good if you could post your solution or even make a PR with your changes.

we are just using simple url fetch. no rocket science involved. But it gives a lot of pain and manual adjustments involved when you want to integrate this in Typescript...

**Comment by alvarosabu** [comment]
Hi @patrick-schneider-latori did you try this workaround suggested here https://github.com/storyblok/storyblok-js-client/issues/682#issuecomment-2028817983 ?

**Comment by patrick-schneider-latori** [comment]
> Hi @patrick-schneider-latori did you try this workaround suggested here [#682 (comment)](https://github.com/storyblok/storyblok-js-client/issues/682#issuecomment-2028817983) ?

Hi @alvarosabu – no, we did not, since we need a robust and working solution for our customers, which all have high traffic. And according to what @remi-freriks it also does not make me happy. Therefore we still stick with native fetch and url parameters, since this solution is also compatible with Cloudflare caching and battle-tested on high traffic websites.

**Comment by alvarosabu** [comment]
Hi @patrick-schneider-latori thanks for getting back, that made absolute sense, let me get it to the team to prioritize it and hopefully work on it soon. 

Thanks for the patience

**Comment by stefanodilegamisunzinet** [comment]
Hi @alexjoverm unfortunately this is not fixed at all. It's still happening when using current Shopify Hydrogen template 2025.1.3 with @storyblok/react v4.6.0

**Comment by mylesthedev** [comment]
Yeah I just ran into this issue when testing on Cloudflare

**Comment by lucasjahn** [comment]
Same here, still happening
