### ISSUE TITLE
RichTextResolver not parsing anchor of Richtext field

### ISSUE THREAD

**Issue by slemont3** [storyblok/storyblok-js-client#719]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

---

## Expected Behavior

After setting an anchor in a Richtext field in Storyblok, I would expect that the RichTextResolver render-function parses the anchor id correctly and sets it on the corresponding HTML element.

## Current Behavior

The anchor can be saved in a Storyblok Richtext field without any problems. The generated JSON File of the Richtext field also contains the anchor. However, once the render-function of RichTextResolver is called with the Richtext field content, the anchor is not parsed and not set to the corresponding HTML element.

## Steps to Reproduce

1. Set an anchor in a Storyblok Richtext field content entry and save the new change. 
2. In an Angular App, the CMS content is dynamically loaded with Angular Universal and the following npm modules are installed: storyblok, storyblok-generate-ts, storyblok-js-client.
3. When retreiving the CMS content, the JSON part containing the anchor of the Richtext field looks like following:

`{
  "type": "doc",
  "content": [
    {
      "type": "paragraph",
      "content": [
        {
          "text": "MyAnchorLinks",
          "type": "text",
          "marks": [
            {
              "type": "anchor",
              "attrs": {
                "id": "anchorid"
              }
            }
          ]
        }
      ]
    }
  ]
}`

4. The content of the Richtext field Json is then parsed with the RichTextResolver render-function in richTextResolver.ts

**Comment by slemont3** [comment]
Hi @ademarCardoso 

Thanks for getting back to this!

We've been using 5.12.0 and also tried with 6.4.1. Alas, we've faced the issue with both versions.

**Comment by ademarCardoso** [comment]
Hello my friend, I was analyzing the behavior of the resolver, and with an anchor with the payload below it produces the output below, transforming the anchor into a `span` tag with `ID`, as expected, could you share with me exactly what HTML is being generated in your tests or exactly the HTML you expect to be generated?

*Test payload*
```json
{
  "type": "doc",
  "content": [
    {
      "type": "paragraph",
      "content": [
        {
          "text": "a long text with a super nice ",
          "type": "text"
        },
        {
          "text": "anchor here",
          "type": "text",
          "marks": [
            {
              "type": "anchor",
              "attrs": {
                "id": "test2"
              }
            }
          ]
        },
        {
          "text": ", and at the end of the text is a normal tag",
          "type": "text"
        }
      ]
    }
  ]
}
```

*Output =>*`<p>a long text with a super nice <span id="test2">anchor here</span>, and at the end of the text is a normal tag</p>`

I used the latest version to check this, but is the same in the `V6.4.1`.

cc: @slemont3

**Comment by slemont3** [comment]
Hi @ademarCardoso 

Many thanks for looking into this. Your example is exactly the behaviour we would have expected too.

Here's the generated JSON and HTML (as you can see, the id="anchor-test"is not set in the <span> tag:

`{
         "type":"paragraph",
         "content":[
            {
               "text":"Nullam",
               "type":"text",
               "marks":[
                  {
                     "type":"anchor",
                     "attrs":{
                        "id":"anchor-test"
                     }
                  }
               ]
            },
            {
               "text":" quis risus eget urna mollis ornare vel eu leo. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Maecenas faucibus mollis interdum. Curabitur blandit tempus porttitor.",
               "type":"text"
            }
         ]
      },`

`<p><span>Nullam</span> quis risus eget urna mollis ornare vel eu leo. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Maecenas faucibus mollis interdum. Curabitur blandit tempus porttitor.</p>`.

We are using V6.4.1.

**Comment by slemont3** [comment]
Hi @ademarCardoso 

Would you happen to have any update on this?

**Comment by slemont3** [comment]
Hi @ademarCardoso 

This issue still exists and it would be greatly appreciated if this could be further analysed as the open issue already exists for a long time and our client would like to use the anchor feature.

Thanks

**Comment by ademarCardoso** [comment]
Hello @slemont3 , i tested with the version `6.8.0` of the js-client and seems to be working, take a look bellow in my test script and the output, i used your JSON to render. Could you please check if it's working in your side ?

```js
const { RichtextResolver } = require('storyblok-js-client')

const doc2= {
  "type": "paragraph",
  "content": [
    {
      "text": "Nullam",
      "type": "text",
      "marks": [
        {
          "type": "anchor",
          "attrs": {
            "id": "anchor-test"
          }
        }
      ]
    },
    {
      "text": " quis risus eget urna mollis ornare vel eu leo. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Maecenas faucibus mollis interdum. Curabitur blandit tempus porttitor.",
      "type": "text"
    }
  ]
}

const resolver = new RichtextResolver()

console.log(resolver.render(doc2))
```

<img width="1439" alt="Screenshot 2024-08-19 at 11 18 35" src="https://github.com/user-attachments/assets/f96f325b-2c50-467c-afb2-5f55deade8ff">

**Comment by slemont3** [comment]
Hi @ademarCardoso 

Thanks for getting back to this. Alas, I had already tested it with the latest version of the client (6.8.2) and it's still not working. Please find more Info below:

JSON received from Stroyblok:

```json
"content": 
  [{
    "text": "Nullam",
    "type": "text",
    "marks": 
      [{
         "type": "anchor",
         "attrs": 
           {
             "id": "anchor-id"
           }
        }
      ]},
      {
        "text": " more text here...",
        "type": "text"
      }
  ]
```

Angular component Typescript:

```typescript
resolver: RichtextResolver = new RichtextResolver();
```

Angular component HTML:

```html
<div [innerHTML]="resolver.render(textBlock)"></div>
```

DOM Element after page rendered:

<img width="247" alt="Screenshot 2024-08-20 at 08 58 45" src="https://github.com/user-attachments/assets/bc5a3006-52b2-4edb-be7d-7b3abe7caea5">



As you can see, the id on the <span> Tag is still missing.

**Comment by ademarCardoso** [comment]
Really strange, i made all of my tests with node or vue, i will check with Angular and i will back here, thanks for sharing the code 👍🏼

**Comment by ademarCardoso** [comment]
I made some tests here and i find the problem, the problem is that the `innerHTML` by [default removes attributes like](https://blog.angular-university.io/angular-innerhtml/) `id` to avoid risks like XSS, to fix that i used `DomSanitizer` and with `bypassSecurityTrustHtml` method we can render directly the HTML, as the provided html from our `storyblok-js-client` is safe to render, with that the id now it's working great.

Bellow i added the component that i used for tests here nad bellow that a image with the result 😄 

I hope this works for you my friend, if not, please send me a message 😃 

```js
import { Component, OnInit } from '@angular/core';
import { RichtextResolver } from 'storyblok-js-client'
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';

@Component({
  selector: 'app-sb',
  standalone: true,
  imports: [],
  template: `
    <div [innerHTML]="htmlContent"></div>
  `,
})
export class SbComponent implements OnInit {
  htmlContent: SafeHtml | null = null;

  constructor(
    private sanitizer: DomSanitizer
  ) {}

  ngOnInit(): void {
    const content = {
      "type": "paragraph",
      "content": [
        {
          "text": "Nullam",
          "type": "text",
          "marks": [
            {
              "type": "anchor",
              "attrs": {
                "id": "anchor-test"
              }
            }
          ]
        },
        {
          "text": " quis risus eget urna mollis ornare vel eu leo. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Maecenas faucibus mollis interdum. Curabitur blandit tempus porttitor.",
          "type": "text"
        }
      ]
    }
    const resolvedHTML = this.resolveRichText(content)
    this.htmlContent = this.sanitizer.bypassSecurityTrustHtml(resolvedHTML)
  }

  resolveRichText(content: any): string {
    const resolver = new RichtextResolver()
    return resolver.render(content)
  }
}
```

<img width="1751" alt="Screenshot 2024-08-20 at 10 28 42" src="https://github.com/user-attachments/assets/bf876625-ec7a-4923-97a1-40d56bd9e143">

**Comment by slemont3** [comment]
Many thanks @ademarCardoso for having a look at it and testing the rendering in Angular. We completely missed the default behaviour by innerHTML. I can confirm that it works when sanitised properly. 

Thanks again for your help, much appreciated!
