### ISSUE TITLE
`automatic` cache clearing doesn't clear cache of published content

### ISSUE THREAD

**Issue by mAAdhaTTah** [storyblok/storyblok-js-client#73]
I have this configured in our Storyblok:

```
  cache: {
    type: 'memory',
    clear: 'auto',
  },
```

I assumed that the `clear: 'auto'` bit would periodically clear the cache, but it appears to only do this for `draft` content requests. Would it be possible to include published content as well?

**Comment by onefriendaday** [comment]
The functionality of auto clearing works best when you use the visual preview as there you always make a call to get the draft version. If you are not using Storyblok's visual preview then I recommend you to setup a route in your application and clear the cache via a published webhook.

**Comment by mAAdhaTTah** [comment]
@onefriendaday That makes sense, and that's how we have it working, although that's definitely not what I got from the docs. I assumed `'auto'` meant it would automatically clear the cache either periodically or when the content changes.

**Comment by djhr** [comment]
@onefriendaday not cool...
