### ISSUE TITLE
Different spelling in esm and usd entry files

### ISSUE THREAD

**Issue by hoersamu** [storyblok/storyblok-js-client#777]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

Currently the `RichtextSchema` is exported as `RichTextSchema` from `entry.umd.ts` and as `RichtextSchema` from `entry.esm.ts`.

I don't think this affects many users, but in our Monorepo this requires a import like this:
```js
import {
  ISbSchema,
  MarkSchema,
  // @ts-ignore
  RichTextSchema,
} from 'storyblok-js-client';
```
which in turn breaks types inference.

Changing this spelling is probably considered a breaking change.

---

## Expected Behavior

Spelling of `Richtext` is consistant

## Current Behavior

See above.

**Comment by hoersamu** [comment]
We have a weird setup where our built application runs in CJS but our tests in ESM and this breaks our setup. Would someone mind taking a look at my proposed fix?

Thanks,
Samu

**Comment by alvarosabu** [comment]
Hi @hoersamu we are going to remove the Richtext-related code from this package towards v7 in favor of https://github.com/storyblok/richtext package.

I would recommend trying the new package and if you have feedback. lets us know

**Comment by hoersamu** [comment]
Thanks. I'll wait till the v7 is released and test it then.

**Comment by alvarosabu** [comment]
I mean @hoersamu there is not going to be any more richtext related code inside of the `storyblok-js-client` from v7 on

**Comment by hoersamu** [comment]
Yeah I know, but if I install the new richtext package to my projects now without waiting for the new v7 I'll end up with both the richtext resolver from the js-client and with the resolver from the new package

**Comment by alvarosabu** [comment]
Oh gotcha @hoersamu but you can actually use the new resolver now if you don't explicitly import the one from the `storyblok-js-client` 

```ts
import { richTextResolver } from '@storyblok/richtext'

const { render } = richTextResolver()

const html = render(doc)

document.querySelector<HTMLDivElement>('#app')!.innerHTML = `
  <div>
  ${html}
  </div>
```
