### ISSUE TITLE
getAll does not resolve dynamic path expression

### ISSUE THREAD

**Issue by maurocolella** [storyblok/storyblok-js-client#81]
Hello Storyblok.

I really like the platform so far.

That having been said, the documentation says:

> **Method Storyblok#getAll**
> With this method you can get all items at once.

> Parameters

> [return] Promise, Array of entities
> path String, Path (can be `cdn/stories, cdn/stories/*, cdn/tags, cdn/datasources, cdn/links`)

But `cdn/stories/*` is not resolved in version `^3.3.0`, and a 404 is returned.

Please advise.

**Comment by DominikAngerer** [comment]
Hey @maurocolella !

Indeed - we need to update the docs on this - by now `cdn/stories/*` is not needed anymore. Feel free to checkout our updated content Delivery API docs here: https://www.storyblok.com/docs/api/content-delivery.
