### ISSUE TITLE
Add inline image in richtext editor

### ISSUE THREAD

**Issue by Youhan** [storyblok/storyblok-js-client#817]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

---

## Expected Behavior

My content team is asking to be able to add content like the following image:
<img width="706" alt="image" src="https://github.com/storyblok/storyblok-js-client/assets/2191898/fbebf61b-6151-4219-a94e-881c0b33bdb2">

I was thinking of adding the stars as images. It looks like the image in the editor becomes a block-level element and if we could add an image as an inline element, it would solve for this use-case. Something like this example that adds inline element in the editor: https://prosemirror.net/examples/dino/

## Current Behavior

Currently, it shows images a block-level elements in the editor
<img width="849" alt="image" src="https://github.com/storyblok/storyblok-js-client/assets/2191898/6519b122-c29e-40d5-8308-017d9e00929b">

## Steps to Reproduce

1. in a richtext editor add a small image
2. add another image
3. the all are block-level

**Comment by alvarosabu** [comment]
Hi @Youhan thanks for reaching out, this seems to be more related to the product itself rather than the js-client. You can submit a feature request through https://support.storyblok.com/ or feel free to re-open if will be more related to the OSS part of Storyblok
