### ISSUE TITLE
Update Cache Version (`cv`) Properly After API Response

### ISSUE THREAD

**Issue by juusopiikkila** [storyblok/storyblok-js-client#823]
The current implementation of caching in the Storyblok JavaScript client does not seem to update the `cv` (cache version) in `cacheVersions` after receiving a new `cv` from the API response when the version is set to "published". This might lead to issues with stale data being served from the cache.

### Expected Behavior
After receiving an API response, if the `cv` from the response is different from what is stored in `cacheVersions` for the given token, the client should:
1. Invalidate the old cache.
2. Update `cacheVersions` with the new `cv` from the response.

### Suggested Fix
Enhance the `cacheResponse` function to update the `cv` in `cacheVersions` after every API response if the value changes. Here is the proposed code snippet to handle this:

```typescript
// Inside cacheResponse function, after receiving the response
if (
    response.data.cv 
    && params.token 
    && cacheVersions[params.token] != response.data.cv
) {
    await this.flushCache()
    cacheVersions[params.token] = response.data.cv
}

```

**Comment by remcoder** [comment]
Just ran into this.. Annoying. Really should be fixed. 

A crude workaround is to clear the cacheversions before requesting data:

```ts
client.clearCacheVersion();
client.get('cdn/stories/mypage')
```

**Comment by codeflorist** [comment]
I believe the culprit lies with this `if`-statement:
https://github.com/storyblok/storyblok-js-client/blob/3592e384637659112d710fe59fe216130dab0350/src/index.ts#L632

```js
          if (
            params.version === 'draft' &&
            cacheVersions[params.token] != response.data.cv
          ) {
            await this.flushCache()
          }
```

I believe this means, a cache-flush is only performed, if `draft` versions are requested. Otherwise i guess the response will stay in memory-cache forever.

I don't know the purpose of limiting the flush-behaviour to `draft` requests. If it is unwanted ot a bug, imho it should be removed.

This has been causing some headaches for quite a while - especially in the Nuxt and nextjs crowd and reports pop up every few weeks in the Discord.

**Comment by codeflorist** [comment]
I think there is also another issue to consider:

What if all API-calls of a website (e.g. 10 stories) are already cached? Then no new API calls to backend will take place at all, meaning the SDK will never know, if there is a new `cv` in the first place.

**Comment by awacode21** [comment]
I have been annoyed with this problem for more than half a year. I think this should really be fixed. Currently you always have to perform a new deployment/server restart to make the published changes visible on the server side.

**Comment by zipme** [comment]
> Just ran into this.. Annoying. Really should be fixed.
> 
> A crude workaround is to clear the cacheversions before requesting data:
> 
> ```ts
> client.clearCacheVersion();
> client.get('cdn/stories/mypage')
> ```

Tried this but doesn't work either

**Comment by codeflorist** [comment]
> > Just ran into this.. Annoying. Really should be fixed.
> > A crude workaround is to clear the cacheversions before requesting data:
> > ```ts
> > client.clearCacheVersion();
> > client.get('cdn/stories/mypage')
> > ```
> 
> Tried this but doesn't work either

Alternative workarounds could be:

Setup the client with cache type `none`:

```js
let Storyblok = new StoryblokClient({
  accessToken: <YOUR_SPACE_ACCESS_TOKEN>,
  cache: {
    type: "none",
  },
});
```

Or state the current timestamp as the cache-version in each if your calls:

```js
Storyblok.get(
  'cdn/stories/home',
  {
    version: 'published',
    cv: Date:now()
  }
)
```

But both solutions effectively disable CDN caching, presumably creating more traffic.

**Comment by pauloamgomes** [comment]
> > > Just ran into this.. Annoying. Really should be fixed.
> > > A crude workaround is to clear the cacheversions before requesting data:
> > > ```ts
> > > client.clearCacheVersion();
> > > client.get('cdn/stories/mypage')
> > > ```
> > 
> > 
> > Tried this but doesn't work either
> 
> Alternative workarounds could be:
> 
> Setup the client with cache type `none`:
> 
> ```js
> let Storyblok = new StoryblokClient({
>   accessToken: <YOUR_SPACE_ACCESS_TOKEN>,
>   cache: {
>     type: "none",
>   },
> });
> ```
> 
> Or state the current timestamp as the cache-version in each if your calls:
> 
> ```js
> Storyblok.get(
>   'cdn/stories/home',
>   {
>     version: 'published',
>     cv: Date:now()
>   }
> )
> ```
> 
> But both solutions effectively disable CDN caching, presumably creating more traffic.

I'm using that solution in the context of next.js (cache type none and passing cv parameter with `Date.now()`) it seems the only way to make the sdk work properly with next.js fetch caching

**Comment by alvarosabu** [comment]
Hi everyone thanks for the detailed explanation.

I just triaged this one, I'm going to take it to plan internally.

Keep you posted
