### ISSUE TITLE
axios error when importing storyblok in Ionic + Angular project

### ISSUE THREAD

**Issue by meghajayakumar** [storyblok/storyblok-js-client#84]
I am trying to include storyblok in my ionic + angular project following this [documentation](https://www.storyblok.com/tp/add-a-headless-cms-to-angular-in-5-minutes). When importing storyblok, I get the below error:

```
ERROR in node_modules/storyblok-js-client/types/index.d.ts:33:49 - error TS2307: Cannot find module 'axios'.
[ng]
[ng]     33 import { AxiosInstance, AxiosProxyConfig } from 'axios'
[ng] Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
[ng] Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
[ng] Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
[ng] Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'
```

Anyone else facing the same issue?

**Comment by VojislavVlasic** [comment]
Hello!
We’ve created JS SDK Beta version for removed Axios and added TypeScript.
https://github.com/storyblok/storyblok-js-client/tree/5.0.0-beta
Please try it out with your projects and let us know if you find any bugs/issues.
