### ISSUE TITLE
Vulnerability in dependency (high)

### ISSUE THREAD

**Issue by fvonellerts** [storyblok/storyblok-js-client#86]
I'm working with `gatsby-source-storyblok` and npm keeps warning me about a security vulnerability in this package.

The issue is a Server-Side Request Forgery in `axios` below version 0.21.1
The advisory is located here: https://www.npmjs.com/advisories/1594

Other than that, best CMS out there!

**Comment by InspectorJapp** [comment]
> https://www.npmjs.com/advisories/1594

Any update on this? I have the same warnng.

**Comment by VojislavVlasic** [comment]
Hello!
We’ve created JS SDK Beta version for removed Axios and added TypeScript.
https://github.com/storyblok/storyblok-js-client/tree/5.0.0-beta
Please try it out with your projects and let us know if you find any bugs/issues.
