### ISSUE TITLE
[Feature Request] remove axios to reduce bundle size in v4

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok-js-client#88]
Hello,

I'd like to suggest that for the upcoming version maybe axios could be replaced with `unfetch` to reduce the bundle size especially for the use in browser environment. Its been used with NextJS and many other packages and is very tiny but still offers probably all functionality needed for this package

Cheers

**Comment by fvonellerts** [comment]
This would also fix the vulnerability in this package caused by axios: https://github.com/storyblok/storyblok-js-client/issues/86

**Comment by K3TH3R** [comment]
This would help with integrating with [Astro](https://www.astro.build) as well. Currently, if you install axios/storyblok-js-client, Astro throws the following error when you try to make a request:
```shell
[executing astro] ReferenceError: XMLHttpRequest is not defined
    at dispatchXhrRequest (/_snowpack/pkg/axios.v0.21.1.js:803:19)
    at new Promise (<anonymous>)
    at xhrAdapter (/_snowpack/pkg/axios.v0.21.1.js:795:10)
    at dispatchRequest (/_snowpack/pkg/axios.v0.21.1.js:1101:10)
``` 
Tried installing the `xmlhttprequest` node library to get this to work, but to no avail. I understand that Axios is supposed to support both browser/node, so I suspect this may be do to Snowpack.

**Comment by dohomi** [comment]
@christianzoppi after you successful reduced the bundle size with `qs` could you have a look at this issue? It would be another great way of reducing the bundle size, as far as I can see there are not many benefits of axios over unfetch or any other isomorphic fetch library

**Comment by dohomi** [comment]
@christianzoppi there is https://github.com/developit/redaxios a 900byte alternative to axios. It shares identical API, the only breaking change would be Interceptors and possibly the timeout as far I can see it in the issues panel.

**Comment by christianzoppi** [comment]
Thanks, @dohomi. I'll let our team know about your suggestions

**Comment by VojislavVlasic** [comment]
Hello!
We’ve created JS SDK Beta version for removed Axios and added TypeScript.
https://github.com/storyblok/storyblok-js-client/tree/5.0.0-beta
Please try it out with your projects and let us know if you find any bugs/issues.
