### ISSUE TITLE
Unclear about how to go about updating story content that has a _uid.

### ISSUE THREAD

**Issue by cronin4392** [storyblok/storyblok-js-client#89]
I am trying to write some code to migrate a field that I changed. I'm using the Storyblok client and the put method. I'm able to update and add content however I am having trouble adding content that requires a _uid field. The only documentation I've found about _uid is [this page](https://www.storyblok.com/faq/what-is-difference-between-story-id-and-uuid).

> They are only unique inside one entry but not across entries. You can not query by them or make references.

Based on what I read I tried just making a random _uid myself but that doesn't work. The content gets saved but it does not appear in the CMS ui. What's the best way to go about generating a correct _uid? Thanks!

Edit:

I dug into some of the storyblok code a bit and found [this](https://github.com/storyblok/example-scripts/blob/0d0e2a6306c6747a7542b3976667c02de2d4f670/import-export-csv/import.js#L8).

```
const { v4: uuidv4 } = require('uuid')
```

I tried using that as well to no avail. The content gets put in, but it does not show up in the CMS itself.

**Comment by VojislavVlasic** [comment]
Hi @cronin4392 do you still need help?
