### ISSUE TITLE
Rate limit back-off

### ISSUE THREAD

**Issue by DaveZIvy** [storyblok/storyblok-js-client#896]
[storyblokurl]: [https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template](https://github.com/storyblok/storyblok-js-client/blob/e49688155bed8f703abc974faf86ade4f21994d1/src/index.ts#L142)

I want to have some sort of back-off for hitting rate limits, but the `retriesDelay` is `private` and hardcoded to 300, so it doesnt' look like I can.

https://github.com/storyblok/storyblok-js-client/blob/e49688155bed8f703abc974faf86ade4f21994d1/src/index.ts#L142

---

## Expected Behavior

I would like to be able to wait a little while after hitting a rate limit during my server build.

## Current Behavior

At the moment, hitting a rate limit will retry in 0.3 seconds.

## Steps to Reproduce
1. Building my storyblok sites in github actions
2. If I'm making enough api calls at the same time, I get an error `Hit rate limit. Retrying in 0.3 seconds.`

![Screenshot 2024-12-13 at 9 44 52 AM](https://github.com/user-attachments/assets/3f232c39-e8f4-48a3-aacb-e9a51e207065)

**Comment by edodusi** [comment]
Hi @DaveZIvy, I don't get why you would like to wait longer than our delay time when throttling with rate limits

**Comment by DaveZIvy** [comment]
@edodusi I've got 13 sites that all live in the same repo and get built at the same time during deploy.

When all 13 are building, we will get hundreds of these "Hit rate limit..." messages and sometimes some of the builds will fail. I figure if we're able to make the timeout longer we can avoid the rate limit and make our build more likely to always pass.

**Comment by edodusi** [comment]
@DaveZIvy I think in your case you should optimize your build, especially a cache. You don't need to hit the API every time you build, especially if you have many websites. The cache configuration depends on the framework you are using, or you can opt for an external cache, I think this will give you the best performances, reduced costs, and also reduce the build failures

**Comment by DaveZIvy** [comment]
@edodusi Thanks for the communication, I appreciate the time it's taking.

How would a cache fix this? When we do a build, we want to include new storyblok content on our site, so wouldn't we have to pull down the storyblok content to see if anything has changed?

Fwiw, all our pages are static and we only hit the storyblok api during the build.

**Comment by edodusi** [comment]
@DaveZIvy this article explains how caching works in Storyblok https://www.storyblok.com/tp/optimize-your-caching-strategy-with-storyblok

In short, you can check the `version` attribute on a space to see if there are changes from your previous check (given you store that param). You can also plug your own object cache to the storyblok-js-client, and use webhooks to implement a purge strategy.

The topic is quite complex, I know that, but I think this is one of the best features an app can implement, reducing the need to hit the API to only when content really changed.

**Comment by DaveZIvy** [comment]
@edodusi I did look into caching, but from what I understand (which may be wrong), the version is at the at the space level and not the story / content / block level.

This poses a problem due to our unusual setup. Our 13 sites all share a single space, and there is a published update to at least 1 of those every day, so the `version` we get back with `https://api.storyblok.com/v2/cdn/spaces/me/?token=xxxx` is always newer then our last build.

I'm honestly not sure how I would handle it if each story had a `cv` but I haven't dug into it yet because I did not think they did.

**Comment by edodusi** [comment]
@DaveZIvy you are correct, the version is tied to the space so you would have a new version every day.

Still, a cache would help you: they are cached by URL (version included) so if you cache them and you share the cache among your 13 website then you will hit the API only the first time, serving the cached content on the others.

You could even leverage our webhook system, implementing a pre-fetching: when you publish a new story, you trigger a webhook and refresh your cache, fetching the new content. Then, when you build, you will get cached content.

**Comment by edodusi** [comment]
@DaveZIvy happy to help, I will close this but if you try something interesting and you find some possible improvements that we can make on the client let me know!
