### ISSUE TITLE
after updating to 4.0.6, the Storyblok v2 endpoint is givng '422 Unprocessable Entity'

### ISSUE THREAD

**Issue by dennispg** [storyblok/storyblok-js-client#90]
After updating from version 3.3.1 to 4.0.6, I began to receive 422 errors from the Storyblok API.

I still don't really fully understand what changed between the versions, I can't find a changelog. I was able to figure out that at some there was a change to a v2 endpoint in Storyblok and there is a way to set the endpoint url in the StoryblokClient constructor. I passed 'https://api.storyblok.com/v1' and it seems to be working fine now.

Is there any available documentation somewhere about all of this? Thanks!

**Comment by onefriendaday** [comment]
Hi! This is probably because V2 is has stricter parameter validations to help developers making less errors. Could you please read in the response body what the error message says?

You can find the docs for V2 here:
https://www.storyblok.com/docs/api/content-delivery/v2

**Comment by dennispg** [comment]
Thanks! I was passing an extraneous parameter to the stories endpoint, and v1 happily ignored it all this time. You set me in the right direction, and thanks for the documentation!
