### ISSUE TITLE
Request for Typescript types: 'storyblok-js-client/dist/rich-text-resolver.*' module

### ISSUE THREAD

**Issue by jplwood** [storyblok/storyblok-js-client#91]
Per the [readme](https://github.com/storyblok/storyblok-js-client#using-the-richtextresolver-separately), we can use the rich text resolver separate from the storyblok client instance. However, in a typescript project that doesn't allow implicit `any` types (i.e., `"noImplicitAny": true,` in the tsconfig.json file), when you try to import the richtext resolver class separately, you get this error:

```console
 Could not find a declaration file for module 'storyblok-js-client/dist/rich-text-resolver.es'. 'path/to/repo/node_modules/storyblok-js-client/dist/rich-text-resolver.es.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/storyblok-js-client` if it exists or add a new declaration (.d.ts) file containing `declare module 'storyblok-js-client/dist/rich-text-resolver.es';`ts(7016)
```

The workaround here is to simply define the library in a typescript declarations file (e.g., `somefile.d.ts` ) like this:

```ts
declare module 'storyblok-js-client/dist/rich-text-resolver.cjs'; 
```

And then make sure typescript knows about the `somefile.d.ts` declarations file via the `tsconfig.json` file's `include` section... for example:
```js
{
  // ...other stuff...
  "include": [
    "**/*.ts",
    // ...other stuff...
  ]
}
```

This appeases typescript regarding this library, but it would be nice if we could just use this out of the box properly with some typing built in.

Thank you in advance!

**Comment by VojislavVlasic** [comment]
Hello!
We’ve created JS SDK Beta version for removed Axios and added TypeScript.
https://github.com/storyblok/storyblok-js-client/tree/5.0.0-beta
Please try it out with your projects and let us know if you find any bugs/issues.
