### ISSUE TITLE
Regression of v4 in some page requests

### ISSUE THREAD

**Issue by dohomi** [storyblok/storyblok-js-client#93]
Hi
After upgrade from 3.3.1 => 4.0.6 I receive following error on some of my API requests of the `.get` API

```
TypeError: Cannot read property 'fieldtype' of null
        at Object.<anonymous>.module.exports._insertLinks (lumen-cms-core/node_modules/storyblok-js-client/dist/index.cjs.js:6:5853)
```
I created a https://github.com/storyblok/storyblok-js-client/pull/92 for this issue. Seems like a regression after v4 upgrade because the same call works in v3

**Comment by dohomi** [comment]
@onefriendaday thanks for merging the PR. Is it possible to roll out a new version to NPM? I have a hard time on Vercel to link to git repos, its kind of a pain in the ass I don't know why I can't point it to the git commit..

**Comment by onefriendaday** [comment]
Sure @dohomi, it got released now ! It just not released automatically because we are using semantic-release for the deployment and therefore you will need to prepend "fix: ..." to your commit message.

**Comment by dohomi** [comment]
thanks!
