### ISSUE TITLE
Retrieve Multiple Stories by UID/* ?depth=1

### ISSUE THREAD

**Issue by nielsbartels** [storyblok/storyblok-js-client#94]
I have a suggestion / question.

I am working on a fairly large website. Multiple languages, multiple slugs / route paths and so on. I am working with Vue / Nuxt, but it's more a general question I think. Feel free to move the issue.

It would be nice to be able to get multiple stories from a certain folder or path, but not by using 'slugs'.
e.g. I would like to render a (sub) / aside navigation from certain pages (or even folders). It's depending on the page I am. Not all pages have aside-nav etc.

So I can get this working with the following options:

- Option one, get all stories, with the starts_with query param (that's not useful for me, because the 'slugs' may change over time).
- Option two, build a component that holds the navigation. Although this would be the answer for most of us, I do not think this is a very dynamic solution (nor user friendly) for the content editor(s) of my client.
- Option three, differ the names of the components, and use the filter queries (also not a good match in my case).
- Option four, just get the current route, check if there is somewhere a boolean (include aside nav or something) and crawl through the current window location (witch leads to option one). hmm
- Option five, get the complete sitemap cdn/links, cache it or something and build javascript methods around it.

What I am missing (or I just can't find it) is an option to get stories from a fixed UID with a certain depth. E.g.

about/
about/company
about/team
about/team/john-doe

I do not want about/team/john-doe, I just don't need to fetch john-doe. I don't want the overhead.
I only want the aside to appear in the other (story)pages and I do not want to fetch to much data. I only want to fetch the data I need.

My suggestion is, to make it possible to retrieve multiple stories: e.g. with a starts_with query param, that allows a UID or a fixed ID and can limit the 'depth' / response of the API call.

Thanks for the comments.

Kind Regards,

**Comment by VojislavVlasic** [comment]
Hi @nielsbartels do you still need help?

**Comment by nielsbartels** [comment]
Nope, I asked this question in 2021. I build something around it...

**Comment by VojislavVlasic** [comment]
Thank you for your response. I'll close this issue now.
Should you need any help, don't hesitate to reach out to us, we should be better now with responding and support.
