### ISSUE TITLE
[v4.0.X]: get('cdn/stories') does not return translated stories

### ISSUE THREAD

**Issue by fcisio** [storyblok/storyblok-js-client#95]
Hi, I had to revert to `v3.3.1` because `get('cdn/stories')` does not return translated stories on `v4.0.X`.

I would always get 404's

Expected behavior:
`get('cdn/stories')` should return stories of all languages.

> Adding specificity did not work either: `get('cdn/stories/de/home')`

**Comment by onefriendaday** [comment]
This https://github.com/storyblok/gatsby-source-storyblok/pull/51 will solve your problem. The V2 api has a new method for receiving languages: https://www.storyblok.com/docs/api/content-delivery/v2#core-resources/stories/retrieve-multiple-stories

It is no longer with the starts_with parameter and instead with a "language" parameter.

**Comment by fcisio** [comment]
Thank using the new parameter does seem to work.

```js
StoryblokService.get(`cdn/stories/${this.props.data.story.slug}`, {
  language: 'fr',
  fallback_lang: 'default',
})
```

You guys should probably update [this doc](https://www.storyblok.com/docs/guide/in-depth/internationalization#get-a-single-story) to reflect the change.
