### ISSUE TITLE
Duplicate identifier 'cacheVersion' in index.d.ts

### ISSUE THREAD

**Issue by akathirvel** [storyblok/storyblok-js-client#97]
I am getting below  error while  running angular 11.2 with story blok 
i  am using 
"storyblok-js-client": "^4.0.8",
"axios": "^0.21.1"

Error: node_modules/storyblok-js-client/types/index.d.ts:181:3 - error TS2300: Duplicate identifier 'cacheVersion'.

181   cacheVersion: number
      ~~~~~~~~~~~~


Error: node_modules/storyblok-js-client/types/index.d.ts:199:3 - error TS2300: Duplicate identifier 'cacheVersion'.

199   cacheVersion(): string
      ~~~~~~~~~~~~

i am followed https://www.storyblok.com/tp/add-a-headless-cms-to-angular-in-5-minutes

**Comment by onefriendaday** [comment]
Thanks for the report. Has been fixed in 4.0.9
